### ISSUE TITLE
[Tarea] - ¿Cómo se supone que debemos obtener los cursos aprobados/reprobados?

### ISSUE THREAD

**Issue by AndresFaure** [IIC2143-2019-2/proyecto#1]
Hola. 
Sospecho que debemos obtenerlos con el archivo _profesores.csv_, sólo quería estar seguro.
Eso, gracias.

**Comment by movaldivia** [comment]
Hola @AndresFaure si es justo como sospechas. Si la nota es menor a 4 significa reprovado, en caso contrario, aprovado.
