### ISSUE TITLE
Error con bundler

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2143-2019-2/proyecto#100]
1
![image](https://user-images.githubusercontent.com/37159294/67126227-ffdff300-f1cc-11e9-8685-7347b909a015.png)
2
![image](https://user-images.githubusercontent.com/37159294/67126166-d45d0880-f1cc-11e9-8f90-8c37eb3d3294.png)
3
![image](https://user-images.githubusercontent.com/37159294/67126109-b2fc1c80-f1cc-11e9-85f0-135b66f3d7f1.png)

Ayuda!

Estoy teniendo los siguientes errores simultaneamente primero cambie el gemfile a 2.5.1 porque me decia que tenia esa version (foto 1), despues  me aparecio que no puede instalarse nokogiri (esto al tratar de agregar boostrap como gema foto 2) y cuando trato sin usar bundler me tira la tercera imagen que mi version de ruby no es la correcta lo cual contradice lo que me dice la foto 1 (no he actualizado ruby ni nada de por medio )

**Comment by daleal** [comment]
Hola! Lo que pasa es que no estás corriendo el comando en tu contenedor de Docker, por lo que la versión de Ruby que está corriendo `bundle install` (la de tu máquina) es distinta a la que está seteada en el proyecto (la de tu contenedor). Para correr el comando, solo debes correr `docker-compose run web bundle install`. En todo caso, cuando haces `docker-compose build` se corre `bundle install` automáticamente. El problema es que cuando cambias la versión que aparece en tu `Gemfile` y luego tratas de usar docker, nada te va a funcionar, porque tu contenedor tiene Ruby 2.6.4 y tu máquina tiene Ruby 2.5.1
