### ISSUE TITLE
Error con enum method

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2143-2019-2/proyecto#101]
Hola! quiero usar devise para diferenciar entre distintos usuarios pero para esto necesito usar el metodo enum, el cual al implementarlo me tira el siguiente error

![image](https://user-images.githubusercontent.com/37159294/67127066-efc91300-f1ce-11e9-96f0-42ae44785324.png)

![image](https://user-images.githubusercontent.com/37159294/67127111-0a9b8780-f1cf-11e9-9e45-c57393b465cf.png)

**Comment by CmPoblete** [comment]
Hola, creo que lo que esta fallando son las comillas. Por lo que tengo entendido, los simbolos no llevan comillas (los simbolos son las variables que empiezan con dos puntos)
