### ISSUE TITLE
Upload a Heroku

### ISSUE THREAD

**Issue by PaoloFabia** [IIC2143-2019-2/proyecto#104]
Hola!

Estoy teniendo problemas para subir mi app a heroku. No me había ocurrido en entregas anteriores. Luego de hacer git push heroku master, me dice: `-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
remote:    More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure`.

Probé utilizando el comando `$ heroku buildpacks:set heroku/ruby`, pero nada. No se si esto les ha ocurrido antes, bacan si alguien me puede orientar sobre cómo solucionarlo.

Gracias de antemano!

**Comment by movaldivia** [comment]
@PaoloFabia en particular no me ha pasado, y buscando me salió el mismo comando que probaste. Lo que si puedes intentar es "retroceder" hasta el último commit que funcione. Luego, cuando lo encuentres puedes ver el código que provoca el error, ya que como dices tu, en algún momento funcionaba. No es la mejor solución, pero si una alternativa hasta que alguien más te pueda ayudar.

**Comment by vjaguilera** [comment]
@PaoloFabia pueden ser muchas las razones del error, pero hay registro para los siguientes casos:
- Verifica si estás pusheando a heroku desde la rama master cuando ejecutas el comando `push`
- Verifica si estás en la carpeta raiz al momento de hacer `push`
Intenta con lo que @movaldivia  dice también, quizás hay algo más que no pudiste ver.

**Comment by daleal** [comment]
Hola! Exactamente qué comando estás usando para hacer `push`?

**Comment by PaoloFabia** [comment]
Muchas gracias por sus respuestas! Lo pude solucionar. Finalmente era un problema del root, pues la app se encontraba dentro de otra carpeta y generaba este error.

Saludos
