### ISSUE TITLE
Cálculo nota de proyecto

### ISSUE THREAD

**Issue by Drpinto1** [IIC2143-2019-2/proyecto#105]
¡Hola!

Ahora que cambió la cantidad de entregas y formato de presentación, ¿cómo se calcula la nota final del proyecto?

Gracias :D

**Comment by jerosalazar** [comment]
Hola! revisa el aviso que mandé por siding y el enunciado de Revisión Final que subí al repo 😊

**Comment by Drpinto1** [comment]
¡Gracias!
