### ISSUE TITLE
docker-compose build se congela. Sin error.

### ISSUE THREAD

**Issue by acpopper** [IIC2143-2019-2/proyecto#106]
Se pega cuando sale
Step 1/8 : FROM ruby:2.6.3
2.6.3: Pulling from library/ruby
y empiezan a descargarse algunos elementos.
A continuación pego el output de docker-compose --verbose build por si es de utilidad:

`compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/home/alan/.docker/config.json', '/home/alan/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /home/alan/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Found entry (registry='https://index.docker.io/v1/', username='acpopper')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/version HTTP/1.1" 200 861
compose.cli.command.get_client: docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
compose.cli.command.get_client: Docker base_url: http+docker://localhost
compose.cli.command.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '19.03.3', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2019-10-08T00:58:31.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'a872fc2f86', 'GoVersion': 'go1.12.10', 'KernelVersion': '5.0.0-37-generic', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.2.10', 'Details': {'GitCommit': 'b34a5c8af56e510852c35414db4c1f4fa6172339'}}, {'Name': 'runc', 'Version': '1.0.0-rc8+dev', 'Details': {'GitCommit': '3e425f80a8c931f88e6d94a8c831b9d5aa481657'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': 'fec3683'}}], Version=19.03.3, ApiVersion=1.40, MinAPIVersion=1.12, GitCommit=a872fc2f86, GoVersion=go1.12.10, Os=linux, Arch=amd64, KernelVersion=5.0.0-37-generic, BuildTime=2019-10-08T00:58:31.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('grupo33proyecto_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/networks/grupo33proyecto_default HTTP/1.1" 404 56
compose.project.build: db uses an image, skipping
compose.service.build: Building web
compose.cli.verbose_proxy.proxy_callable: docker build <- (path='/home/alan/Documents/Grupo33-proyecto', tag='grupo33-proyecto_web', rm=True, forcerm=False, pull=False, nocache=False, dockerfile=None, cache_from=None, labels=None, buildargs={}, network_mode=None, target=None, shmsize=None, extra_hosts=None, container_limits={'memory': None}, gzip=False, isolation=None, platform=None)
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: Sending auth config ('https://index.docker.io/v1/')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/build?t=grupo33-proyecto_web&q=False&nocache=False&rm=True&forcerm=False&pull=False HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker build -> <generator object APIClient._stream_helper at 0x7f52fad9d620>
Step 1/8 : FROM ruby:2.6.3
2.6.3: Pulling from library/ruby
4ae16bd47783: Downloading [=========>                                         ]  9.698MB/50.38MB
bbab4ec87ac4: Downloading [=================================================> ]  7.769MB/7.804MB
2ea1f7804402: Waiting
96465440c208: Waiting
6ac892e64b94: Waiting
1f85508cf3dd: Waiting`

Gracias de antemano y perdón por el mal timing del problema, pero no se que más intentar

**Comment by daleal** [comment]
Hola! Estás en linux? Si es así, trata de hacer un downgrade del kernel (si usas una distribución distinta a ububtu). Si no, trata de hacer un downgrade de la versión de docker. Cualquier cosa sigue esta issue! (El problema probablemente se debe a que algunas versiones de docker funcionan mal con algunas versiones del kernel de linux y quedan con mal acceso a internet entonces no puedes pullear la imagen base)

**Comment by acpopper** [comment]
No se como se arreglo.
Borré todos los contenedores, imágenes y volúmenes de docker, despues hice un sudo service docker restart, reinicié la máquina virtual. Y volví a hacer build. Esta vez se despegó igual después de unos 10 minutos pero terminó el build y ahora funciona bien de nuevo.
Dejo como lo solucioné por si a alguien más le pasa.
Muchas gracias igual!
