### ISSUE TITLE
[Tarea] Casos de Uso Error Csv

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2143-2019-2/proyecto#11]
Hola!

Aparte del ejemplo dado en el enunciado en que casos debería llamarse a la función `error_csv`?

Por ejemplo, en general es posible que cuando nos pasén un ID, sea de un curso un profesor o un alumno, sea el ID de otra entidad en vez de la que esperamos? O también puede que recibamos más argumentos de los necesarios etc etc.

Gracias!

**Comment by jerosalazar** [comment]
Hola, no he subido la nueva versión. Pero puedes completarlo tu si quieres. Simplemente ten en cuenta de que no pasará ese error con la versión final que usaremos para probar la tarea

**Comment by lldavico** [comment]
Hola,

O sea debemos asumir que el tipo de error que podría existir en el input solo se reduce a un id inexistente para un profesor, curso o alumno?

**Comment by vjaguilera** [comment]
Los tipos de errores que deberían manejar como mínimo son:
- ID incorrecto
- Inputs de funciones inválidos (pueden ser bastantes casos, pero **se solicitarán 2** de manera fija: tipo de dato incorrecto, input no ingresado)
- Errores de formato de la pregunta (El formato de la pregunta en el archivo está errada: **cursos_aprobados, 4** sería un ejemplo)

Traten de imaginar que esta tarea los introduce al lenguaje del proyecto, donde deberán imaginarse todos los posibles errores que pueden existir al momento de recibir información en la interacción del usuario.
