### ISSUE TITLE
[Docker] Problema al correr la aplicación de rails

### ISSUE THREAD

**Issue by nep0s** [IIC2143-2019-2/proyecto#12]
Hola,
el terminal de ubuntu se me queda atascado en un loop cuando trato de correr la aplicación como dice el readme de example.
Luego de crear la database, corro el comando `sudo docker-compose up`.
Como respuesta, el terminal responde en un loop con la misma línea:

`db_1   | 2019-08-31 17:13:33.447 UTC [54] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied`

Gracias de antemano

**Comment by daleal** [comment]
Hola! Probaste ejecutando `sudo chown -R $USER:$USER .` ?

**Comment by daleal** [comment]
Hola! Luego de investigar por un rato, llegué a la conclusión de que ese archivo solamente recolecta estadísticas de la base de datos, por lo que no es importante para la ejecución de tu aplicación. Por otro lado, el terminal **debe** quedar ocupado cuando haces `docker-compose up`, por lo que no es que tu terminal quede atascado en un loop, sino que la aplicación está corriendo y la base de datos avisa (múltiples veces) que no es capaz de recolectar las estadísticas. Intenta entrar a `localhost:3000` para ver si estás _"on rails"_ (`yay!`)

**Comment by nep0s** [comment]
Me aparecía un mensaje de error al entrar a `localhost:3000`, pero después de tratar un par de veces y viendo otra issue pude solucionar el problema. Gracias!
