### ISSUE TITLE
Problema conectar bd

### ISSUE THREAD

**Issue by robertov1** [IIC2143-2019-2/proyecto#13]
Hola,

En la línea: "Connect the database (replace the content of config/database.yml with the following, change {example} with your app's name)" del ejemplo de la ayudantía, donde está "config/database.yml" para poder reemplazar el contenido??

Saludos!

**Comment by jerosalazar** [comment]
Hola!

Una vez creado el proyecto de rails (cuando corres ... rails new ...) se crean varias carpetas. En una de esas carpeta llamada config hay un archivo llamado database.yml, ese es el que tienes que editar

**Comment by robertov1** [comment]
Esas carpetas se deberían haber creado dentro de la carpeta donde estaban los otros archivos??

Corrí  "docker-compose run web rails new . --force --no-deps --database=postgresql", se ejecutó completo. Después corrí: "docker-compose build". Pero no se creó ninguna carpeta

Que puede estar mal?

Saludos!

**Comment by jerosalazar** [comment]
Al correr rails new se crearon muchas carpetas y archivos en la carpeta donde guardaste los archivos de setup. `build` no crea carpetas, solo instala las dependencias y hace otras cosas por detrás

**Comment by jmsilvas** [comment]
@robertov1 me acaba de pasar lo mismo, encontraste la carpeta?

**Comment by robertov1** [comment]
@jmsilvas Me cambié a ubuntu y funciona perfecto. No pude hacerlo en windows

**Comment by quememo** [comment]
Encontré esto:
[https://medium.com/@adrianlpad/gu%C3%ADa-instalar-rails-5-con-docker-windows-linux-mac-75d2c344fc41](url)

Se parece a lo que está subido y funciona en Windows 10
