### ISSUE TITLE
[Docker] Duda "example"

### ISSUE THREAD

**Issue by matumartinez** [IIC2143-2019-2/proyecto#14]
Hola,

Seguí todos los pasos de la plantilla de la carpeta "example", pero cuando intenté correr la aplicación con "docker-compose up". Ocurre esto:

db_1   | PostgreSQL init process complete; ready for start up.
db_1   | 
db_1   | 2019-08-31 18:04:21.505 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-08-31 18:04:21.505 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-08-31 18:04:21.510 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-08-31 18:04:21.599 UTC [52] LOG:  database system was shut down at 2019-08-31 18:04:21 UTC
db_1   | 2019-08-31 18:04:21.632 UTC [1] LOG:  database system is ready to accept connections

Estas son las últimas 7 líneas del terminal (estoy usando Mac) y se queda pegado. ¿Alguna sugerencia de cómo se resuelve?

muchas gracias de antemano

**Comment by jerosalazar** [comment]
Si te sale en la ultima linea `database system is ready to accept connections` es porque tu aplicación está funcionando. Ahora debería salir la pagina de "Yay you're on rails" si te metes a `localhost:3000`
