### ISSUE TITLE
[Docker][Problema con la creación de la db]

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2143-2019-2/proyecto#15]
Hola!
Sucede que he estado desde el jueves tratando de hacer correr docker en mi sistema operativo (ubuntu 18.04) y no puedo crear la base de datos en docker, de hecho pense inicialmente que era un problema de docker, asi que lo reinstale, pero no cambio. Despues cambie de carpeta para hacer de nuevo todo el proceso del tutorial, pero tampoco ha funcionado.
Ademas, encuentro muy raro el error que tira, porque revisando a la carpeta que hace referencia el error si existe, pero no comprendo cual es el error.
Adjunto pantallazo del error.

![Selection_001](https://user-images.githubusercontent.com/42159123/64069344-d61b3e80-cc15-11e9-9d8e-9f8ca3eb93c2.png)
Cualquier ayuda se agradece.

**Comment by daleal** [comment]
Hola! Pegaste en la carpeta `config/database.yml` lo que dice el README de ejemplo?

**Comment by arbiocanpion** [comment]
Si, de hecho probe tambien con lo que indicaban en la issue [https://github.com/IIC2143-2019-2/proyecto/issues/7](url) y realice el procedimiento que se indicaba en el readme sobre si docker-compose run web rails db:create te tiraba error, pero nada.

**Comment by daleal** [comment]
Puedes mandar lo que tienes dentro de tu `Dockerfile` y lo que tienes dentro de tu `docker-compose.yml`?

**Comment by arbiocanpion** [comment]
Acabo de volver a copiar y pegar lo que indicaba el example y me funciono.
¡Muchas gracias por la preocupación!

**Comment by arbiocanpion** [comment]
Para agregar, la diferencia esta vez con las anteriores, fue que pegue literalmente todo junto lo que aparecia en el readme del example en database.yml, ya que el archivo original que me aparecia, venia con varias lineas extras que no se porque saldrían.
