### ISSUE TITLE
[Docker] Duda localhost:3000

### ISSUE THREAD

**Issue by cristianoberpaur** [IIC2143-2019-2/proyecto#16]
Estoy usando linux, seguí todos los pasos y mis últimas lineas son: 
db_1   | 2019-08-31 23:35:29.265 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-08-31 23:35:29.265 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-08-31 23:35:29.395 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-08-31 23:35:30.118 UTC [23] LOG:  database system was shut down at 2019-08-31 23:35:00 UTC
db_1   | 2019-08-31 23:35:30.280 UTC [1] LOG:  database system is ready to accept connections

Por lo que pareciera que está funcionando bien, pero cuando me meto a localhost:3000 me aparece lo siguiente:
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Alguna idea de lo que puede estar pasando ?
Agradecería mucho si me pueden ayudar.

**Comment by daleal** [comment]
Hola! Al momento de hacer `docker-compose run web rails db:create`, el output del comando debería haber sido algo como lo siguiente:

```bash
'Created database [app_name]_development'
'Created database [app_name]_test'
```
Puedes confirmar que ese fue el output? De lo contrario, detén el contenedor (`docker-compose down`), intenta crear las bases de datos nuevamente (`docker-compose run web rails db:create`) y si el output ahora si es el esperado, entonces levanta el servidor (`docker-compose up`) e intenta entrar a `localhost:3000`.

**Comment by cristianoberpaur** [comment]
Efectivamente ese no fue el output, hice el docker-compose down, pero el output es el mismo:

Creating network "example_default" with the default driver
Creating example_db_1 ... done
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create 'example_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by daleal** [comment]
Asumo que ese es el output del comando `docker-compose run web rails db:create`. Podrías copiar y pegar el contenido de tus archivos `Dockerfile`, `docker-compose.yml` y `config/database.yml`?

**Comment by cristianoberpaur** [comment]
Sí, si era el output de _docker-compose run web rails db:create_. Yo clone la repo desde github y cambie nada de los archivos, acá van.

_Dockerfile_:

FROM ruby:2.6-rc
RUN apt-get update &&\
    # add support to unicode chars from keyboard: ç,ã,ô:
    apt-get install -y locales &&\
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen &&\
    rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8
RUN apt-get update -qq && apt-get install -y postgresql-client
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
        && apt-get install -y nodejs

ENV APP_HOME /example

RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install
COPY . $APP_HOME

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]

_docker-compose.yml_:

version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/example
    ports:
      - "3000:3000"
    depends_on:
      - db

_config/database.yml_:

# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: example_development

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: example

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: example_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: example_production
  username: example
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>

**Comment by cristianoberpaur** [comment]
Sí, si era el output de *docker-compose run web rails db:create*. Acá van los archivos:

*Dockerfile*:

FROM ruby:2.6-rc
RUN apt-get update &&\
    # add support to unicode chars from keyboard: ç,ã,ô:
    apt-get install -y locales &&\
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen &&\
    rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8
RUN apt-get update -qq && apt-get install -y postgresql-client
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
        && apt-get install -y nodejs

ENV APP_HOME /example

RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install
COPY . $APP_HOME

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]

**Comment by cristianoberpaur** [comment]
Sí, si era el output de  *docker-compose run web rails db:create*. Acá van los archivos. Les borre los comentarios porque al pegarlos acá quedan gigantes por el hashtag.

*Dockerfile*:
FROM ruby:2.6-rc
RUN apt-get update &&\
    
    apt-get install -y locales &&\
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen &&\
    rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8
RUN apt-get update -qq && apt-get install -y postgresql-client
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
        && apt-get install -y nodejs

ENV APP_HOME /example

RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install
COPY . $APP_HOME


COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000


CMD ["rails", "server", "-b", "0.0.0.0"]


*docker-compose*.yml*:
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/example
    ports:
      - "3000:3000"
    depends_on:
      - db


*config/database.yml*:
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: example_development

test:
  <<: *default
  database: example_test

production:
  <<: *default
  database: example_production
  username: example
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>

**Comment by daleal** [comment]
Reemplaza el contenido de tu `config/database.yml` por lo siguiente:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: example_development


test:
  <<: *default
  database: example_test
```

Luego, vuelve a intentar hacer la base de datos con `docker-compose run web rails db:create`. Debería salirte el output esperado. Si es así, puedes levantar el servidor con `docker-compose up` y ya deberías estar _"on rails"_ (`yay!`)

**Comment by cristianoberpaur** [comment]
Ahora si me funcionó. Muchas gracias, estuve mucho rato tratando pero por fin funcionó =):
