### ISSUE TITLE
[Ruby y Dockers] Insatalación

### ISSUE THREAD

**Issue by fivaldivia** [IIC2143-2019-2/proyecto#17]
Hola, quería saber si es factible instalar Ruby y Docker en Windows 10 o es preferible particionar el disco duro? Gracias

**Comment by daleal** [comment]
Hola! **Si** es posible instalar docker en Windows! Sin embargo, si la instalación te da problemas, tienes 2 opciones. Una es particionar el disco duro como bien dices (suena complejo pero está bien documentado en internet, hay varios tutoriales). Esta opción te asegura la mejor experiencia como usuario del computador a lo largo del semestre. La segunda opción es usar una [máquina virtual](https://github.com/IIC2143-2019-2/proyecto/wiki/M%C3%A1quina-Virtual). Esta opción tiene la ventaja de ser más simple de instalar, pero tiene la desventaja de ser bastante lento.

**Comment by fivaldivia** [comment]
Hola, seguí los pasos para particionar mi disco duro y a la hora de instalar Ubuntu no me sale la opción de instalar junto a Windows. No se como hacerlo para que me aparezca ya que me debería aparecer, tengo el computador Dell Inspiron 15, si alguien sabe como hacerlo me sería de gran ayuda. Dejo adjunta la imagen de lo que me sale a la hora de instalar Ubuntu.
![WhatsApp Image 2019-09-01 at 19 18 59](https://user-images.githubusercontent.com/42453679/64083416-d0912780-cced-11e9-85a7-ea47e5df3a4e.jpeg)

Muchas gracias!!

**Comment by daleal** [comment]
Podrías entrar a la consola de Windows, escribir `diskmgmt`, apretar `enter` y mandar una foto de lo que se abre?

**Comment by fivaldivia** [comment]
OK, me salio esto:
![image](https://user-images.githubusercontent.com/42453679/64129709-cd4c7900-cd8b-11e9-84a5-cf9bf3723340.png)

**Comment by daleal** [comment]
Mi apuesta es que linux se está tratando de instalar en tu disco duro y no en tu disco en estado sólido. Por lo que veo, no tienes mucho espacio en tu disco en estado sólido, así que instalar linux ahí se ve difícil. Lo que puedes hacer es hacerle _shrink_ a tu disco `DATA` en unos 200GB (para que lo use el nuevo sistema operativo) y después volver a intentar instalar linux (en la instalación te debería dar la opción de instalarse en esos 200GB y no borrar **todo** el disco). El problema es que si haces eso, probablemente tengas que entrar a la BIOS cada vez que quieras cambiar entre sistemas operativos, porque `grub` no va a detectar Windows, solamente va a detectar linux debido a que quedará instalado junto a ese sistema operativo en el disco duro mientras que Windows está en la _SSD_ (`grub` es algo así como un _"boot menu"_ que se instala junto con linux)

**Comment by fivaldivia** [comment]
Hacerle _shrink_ te refieres a reducirle el volumen osea hacerle una partición?

**Comment by daleal** [comment]
Hola! Si, pero te recomiendo que no _formatees_ el espacio libre que dejas al hacer _shrink_, ya que el instalador de Ubuntu hace eso por tí y sabe exactamente qué formato ponerle a la partición nueva.

**Comment by fivaldivia** [comment]
Pucha, sigue saliendome lo mismo de la vez anterior, y si me meto a  "Más opciones" me sale esto, talvez sepas que hacer:
![image](https://user-images.githubusercontent.com/42453679/64135367-ab67ec00-cdb5-11e9-921e-d8725bedcdc5.png)
Aparte tengo un link(https://www.genbeta.com/paso-a-paso/linux-paso-a-paso-instalar-ubuntu-con-dual-boot-junto-a-windows-10) que podría ser de ayuda pero tampoco abría que poner en la parte donde sale:
![image](https://user-images.githubusercontent.com/42453679/64135390-e9fda680-cdb5-11e9-9ee9-5447e3b0cee3.png)
Si sabes porfavor dime, ya que llevo demaciados días en esto y no quiero que le pase nada a mi computador.

**Comment by daleal** [comment]
La verdad es que no sabría cómo resolverlo sin riesgo, por lo que te recomiendo usar una máquina virtual :( lo lamento.
