### ISSUE TITLE
[Dockers] Duda de cambio en archivos

### ISSUE THREAD

**Issue by MGilB** [IIC2143-2019-2/proyecto#18]
Tengo un problema, al copiar la carpeta example, le cambié el nombre como hay que hacer y también cambie los archivos el nombre de la carpeta y al correr el comando 
`docker-compose run web rails new . --force --no-deps --database=postgresql` 
Me aparece el siguiente error
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by bgsamilla** [comment]
Tambien me pasó, intenta anteponer sudo
Eso lo arregla en linux. (No se si funciona en mac o windows)

PD: no soy ayudante del curso
