### ISSUE TITLE
[Docker] Problema en "create a rails app"  - Windows

### ISSUE THREAD

**Issue by camichavez** [IIC2143-2019-2/proyecto#19]
Hola! Estoy tratando de seguir los pasos que nos dieron en el README de la ayudantía de este viernes pero al utilizar el comando `docker-compose run web rails new . --force --no-deps --database=postgresql` me sale esto (ocupo windows) :
![image](https://user-images.githubusercontent.com/37157327/64081401-4c7b7780-ccce-11e9-9962-8c3cae850a87.png)
No sé si tendrá que ver, pero antes de eso (al poner el mismo comando) me salia 
`debconf: delaying package configuration, since apt-utils is not installed`. 

He buscado en internet pero no he llegado a ninguna solución, no sé si tendrán alguna pista o si le ha pasado a alguien antes.

Muchas gracias!

**Comment by vjaguilera** [comment]
Hola!
Podrías mandar una foto de tu archivo _Dockerfile_ ?

**Comment by camichavez** [comment]
![image](https://user-images.githubusercontent.com/37157327/64085996-ba8e6180-cd03-11e9-9c44-c267722c433b.png)

**Comment by camichavez** [comment]
Hola! perdón pero he intentado y aún me sale esto :(

**Comment by Polea012** [comment]
Hola, estás ocupando docker toolbox para el ambiente docker?

**Comment by camichavez** [comment]
hola! sii

**Comment by Polea012** [comment]
El error parece referirse a un problema dentro de la máquina linux. Aquí hay una issue en docker al respecto de alguien que tuvo el mismo problema.
https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025

Esta bastante extraño el problema, seguiremos averiguando que podría ser.

**Comment by camichavez** [comment]
Ya había entrado a esa issue. Leí también por ahí que podía ser algo relacionado con que windows requiere algún implemento para poder leer archivos .sh. Descargué Cygwin pero no logré llegar más lejos y el error sigue.

**Comment by lucasvsj** [comment]
@Polea012, ¿han podido llegar a alguna solución respecto a éste problema? 
Resulta que yo traté varias cosas que recomendaban hacer, modificar archivos Dockerfile, entrypoint.sh y cambiar el End of Line Sequence de CRLF a LF en el archivo entrypoint.sh (lo cual parecía solucionarle el problema a varios), pero ninguno de ellos me resultó.
Creo que el error que sale es por el comando:
`RUN chmod +x /usr/bin/entrypoint.sh`
del Dockerfile (ya que al escribirlo en cmd sale un error muy parecido).
Revisé el directorio usr/bin mediante cmd (pudiendo acceder sin problema) y ahí vi que no se encontraba el archivo entrypoint.sh. Mi intuición dice que lo agregue manualmente, pero no se como tener acceso a este directorio de otra forma aparte de cmd.
Por favor, cualquier solución serviría inmensamente, ya que todabía no puedo crear la app.
De antemano muchas gracias
