### ISSUE TITLE
Problema con instalación de Rails 

### ISSUE THREAD

**Issue by fpaez7** [IIC2143-2019-2/proyecto#2]
En verdad no se que hacer probe todo lo que san google me mostro pero no puedo instalar rails 
`$ ruby -v`
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
`$ rails -v`
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.
`$ sudo gem install rails`
Password:
Successfully installed rails-6.0.0
Parsing documentation for rails-6.0.0
Done installing documentation for rails after 0 seconds
1 gem installed
`$ rails -v`
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.

**Comment by jerosalazar** [comment]
Hola!

En el proyecto vamos a trabajar con Docker, por lo que no es necesario que instales Rails en tu computador, ya que al ocupar docker todas las dependencias necesarias estarán instaladas en un contenedor donde estará su aplicación. Esto quiere decir que, ocupando el template que acabo de subir a la carpeta example (que explicaremos este viernes en la ayudantía) Docker instalará las versiones necesarias de ruby, rails y cualquier otra librería/dependencia que necesiten.

Este viernes tendremos una ayudantía sobre Docker donde explicaremos todo sobre este tema, pero si quieres revisar un poco como funciona Docker puedes revisar este [link](https://opensource.com/resources/what-docker).

**Comment by KnowYourselves** [comment]
Hola @jerosalazar!

Yo por mi parte ya instalé ruby y rails en mi notebook, supongo que esto no presentará ningún problema al momento de trabajar con Docker?

De antemano, gracias!

**Comment by daleal** [comment]
@fpaez7 no necesitas tener la gema instalada en tu sistema (no vamos a usar nada que no esté en la imágen de docker), pero si quieres instalarla de todas formas, instálala con `gem install rails` en vez de usar sudo (probablemente ahora puedes correr `sudo rails -v` y cuando la instales sin ser root vas a poder correr `rails -v`).
@KnowYourselves no debería presentar ningún problema.
Saludos!
