### ISSUE TITLE
[Docker] - Versiones de ruby, docker compose, Linux

### ISSUE THREAD

**Issue by dmelberg** [IIC2143-2019-2/proyecto#20]
Hola, estoy trabajando en Linux. Segui todos los pasos del ejemplo y cuando corro
`sudo docker-compose run web rails new . --force --no-deps --database=postgresql`
Me tira este error:
![Screenshot from 2019-09-01 16-17-59](https://user-images.githubusercontent.com/48286356/64081821-25c03f80-ccd4-11e9-83d3-64aeb6e15399.png)
Me meti a revisar y mi version instalada es 2.6.3 entonces deje el archivo Gemfile y el ruby-version con esa version y aun me tira ese error.
Aqui otra foto de los distintos resultados cambiando la version en los archivos y probando hacer lo que pide de "bundle install".
![Screenshot from 2019-09-01 16-20-56](https://user-images.githubusercontent.com/48286356/64081844-83ed2280-ccd4-11e9-9446-e599803e87a3.png)

**Comment by daleal** [comment]
Hola! Podrías mandar el contenido de tu `Gemfile`, el contenido de tu `Gemfile.lock` y los archivos en la raíz de tu repositorio?

**Comment by movaldivia** [comment]
@dmelberg 
En el `Dockerfile` prueba cambiar el 2.6 por un 2.6.x 
Y luego reconstruye avisa si te sirvió

**Comment by dmelberg** [comment]
Hola, si lo cambio por 2.6.x en el Dockerfile para lo mismo :( Mando los archivos
No me deja adjuntar esos formatos de archivos, pero esto dicen:
Gemfile:
`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
`

El gemfile lock:
`GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.3)
      actionpack (= 5.2.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.3)
      actionview (= 5.2.3)
      activesupport (= 5.2.3)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.3)
      activesupport (= 5.2.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.3)
      activesupport (= 5.2.3)
      globalid (>= 0.3.6)
    activemodel (5.2.3)
      activesupport (= 5.2.3)
    activerecord (5.2.3)
      activemodel (= 5.2.3)
      activesupport (= 5.2.3)
      arel (>= 9.0)
    activestorage (5.2.3)
      actionpack (= 5.2.3)
      activerecord (= 5.2.3)
      marcel (~> 0.3.1)
    activesupport (5.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    bindex (0.8.1)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    builder (3.2.3)
    byebug (11.0.1)
    capybara (3.28.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.5)
      xpath (~> 3.2)
    childprocess (1.0.1)
      rake (< 13.0)
    chromedriver-helper (2.1.1)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    erubi (1.8.0)
    execjs (2.7.0)
    ffi (1.11.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    io-like (0.3.0)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    msgpack (1.3.1)
    nio4r (2.5.1)
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    pg (1.1.4)
    public_suffix (4.0.1)
    puma (3.12.1)
    rack (2.0.7)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.3)
      actioncable (= 5.2.3)
      actionmailer (= 5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      activemodel (= 5.2.3)
      activerecord (= 5.2.3)
      activestorage (= 5.2.3)
      activesupport (= 5.2.3)
      bundler (>= 1.3.0)
      railties (= 5.2.3)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.2.0)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.2.3)
      actionpack (= 5.2.3)
      activesupport (= 5.2.3)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (12.3.3)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    regexp_parser (1.6.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.3)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.1.0)
      railties (>= 5.2.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.142.3)
      childprocess (>= 0.5, < 2.0)
      rubyzip (~> 1.2, >= 1.2.2)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.9)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  bootsnap (>= 1.1.0)
  byebug
  capybara (>= 2.15)
  chromedriver-helper
  coffee-rails (~> 4.2)
  jbuilder (~> 2.5)
  listen (>= 3.0.5, < 3.2)
  pg (>= 0.18, < 2.0)
  puma (~> 3.11)
  rails (~> 5.2.3)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

RUBY VERSION
   ruby 2.6.3p62

BUNDLED WITH
   1.17.3
`
Y lo ultimo no entendi... te mando todos los archivos en mi repo? los nombres?
Gracias de antemano :smile:

**Comment by daleal** [comment]
Hola! Si, la idea es que me mandes los archivos que están en la raíz de tu repo. Por ejemplo, el `Gemfile` y el `Gemfile.lock` deberían estar en la raíz de tu repo. En todo caso, si en la raíz de tu repo también tienes algunas carpetas creadas (entre ellas `app`, `bin`, `db`, etc), entonces haz lo siguiente:

- Asegúrate de que la primera línea de tu `Dockerfile` dice `FROM ruby:2.6-rc`
- Borra **todo** el contenido de tu `Gemfile.lock` (_i.e._ deja un archivo vacío)
- Cambia la línea de tu `Gemfile` que dice `ruby '2.6.3'` para que ahora diga `ruby '2.6.0'`
- Si tienes un archivo llamado `.ruby-version`, **reemplaza** su contenido con `ruby-2.6.0`
- Ejecuta el comando `docker-compose build`

Una vez terminada la secuencia, deberías estar _"on rails"_ (`yay!`). En caso de que en la raíz de tu repositorio **no** tengas ninguna carpeta de las mencionadas (`app`, `bin`, `db`, etc), **borra** el repositorio, vuelve a clonar la carpeta de ejemplo que les entregamos y vuelve a ejecutar la secuencia de pasos descritos en el `README`.

**Comment by robertov1** [comment]
Hola @daleal , tengo un problema parecido.

Con ruby '2.6.3' en el Gemfile:
- Se sube bien a heroku con git push heroku master
- Error al hacer sudo docker-compose up --> Bundler::RubyVersionMismatch: Your Ruby version is 2.6.0, but your Gemfile specified 2.6.3

Con ruby '2.6.0' en el Gemfile:
- Al hacer git push heroku master, error --> Your Ruby version is 2.6.3, but your Gemfile specified 2.6.0
- Se sube bien al hacer sudo docker-compose up

Mi versión de ruby cuando pongo: ruby -v es 2.6.3

En el repositorio de mi grupo (Grupo01) están todos los archivos de la aplicación

Como puedo solucionar este problema?

Gracias!

**Comment by daleal** [comment]
Hola! El problema probablemente se debe a que estás deployeando **sin usar docker**, cosa que está mal. Debes subirla usando Docker (ya hay una issue sobre el tema), haciendo calzar las versiones de ruby que se encuentran en el `Gemfile` y en el `Dockerfile`.
