### ISSUE TITLE
[Docker]- Problema al crear la database

### ISSUE THREAD

**Issue by rsnegrin** [IIC2143-2019-2/proyecto#21]
Hola !
Luego de reemplazar el contenido del archivo _'config/database.yml'_ con lo que aparece en el README.md del _examplẹ̣_ , trato de usar el comando _'docker-compose run web rails db:create'_ y me arroja el siguente error : 

**Starting template_db_1 ... done 
rails aborted!
YAML syntax error occurred while parsing /example/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 1 column 5**

Busqué el error en Google pero no logro encontrar nada. 
Estoy copiando exactamente lo mismo que dice en el README (cambiando example por el nombre de mi app)

Ojalá me puedan ayudar!
Gracias

**Comment by jerosalazar** [comment]
Hola, el error parece ser un problema con la indentación. Trata de borrar las indentaciones y recrearlas solo con espacios (quizás tu editor de texto las tomó como tabs). 

PS: borraste los brackets que salen en el readme para el nombre de la app? Es decir {example}_development -> proyecto_development

**Comment by rsnegrin** [comment]
Si borré los brackets  y ahora que me aseguré que sean espacios arroja el siguente error :


**Caused by:
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 2 column 12**

El lugar donde se supone que está el error es justo donde aparece `&default`

**Edit:**
**¡Solucionado!**
Simplemente borré el YAML del inició y funcionó!
Gracias
