### ISSUE TITLE
[Docker] Duda nombre de app y database

### ISSUE THREAD

**Issue by dhvasquez** [IIC2143-2019-2/proyecto#22]
Hola, quería saber si el nombre de la aplicación debe ser el mismo entre los integrantes del grupo, o si da lo mismo.

De antemano gracias 😃

**Comment by daleal** [comment]
Hola! Debido a que uno de los integrantes debe _setear_ el proyecto y los demás deben hacer un _pull_ y solamente hacer `build` (como dice al final del `README` entregado), realmente no debería existir ninguna diferencia con respecto al nombre de la aplicación (ya que solamente uno de los integrantes debe crear la app).
