### ISSUE TITLE
[Tarea] Input y Output para verificar consultas

### ISSUE THREAD

**Issue by lldavico** [IIC2143-2019-2/proyecto#23]
Hola!

Existe la posibilidad de que suban archivos de prueba para verificar si estamos realizando bien las consultas? Algo así como el ejemplo del input `acciones.csv` y `output.txt` en el enunciado de la tarea, pero con los datos que disponemos?

Gracias!

**Comment by jerosalazar** [comment]
Hola, en siding están los archivos con la información de los alumnos y profesores, junto con el de acciones. El archivo de output no lo subiremos para que vean por su cuenta lo que su programa debe imprimir
