### ISSUE TITLE
Tarea alumnos_aprobados() nombres alumnos

### ISSUE THREAD

**Issue by tomascortes** [IIC2143-2019-2/proyecto#24]
Hola, en la tarea se menciona que la clase `Curso`, debe tener la funcion alumnos_aprobados, la cual dice que debe escribir los nombres de los alumnos que aprobamos pero segun el enunciado esta clase se pide que tenga solo id de alumnos y notas, por lo que no se si se quiere que en realidad sea la id_alumno o que en un principio le demos los nombres a la clase `Curso`

Gracias

**Comment by jerosalazar** [comment]
Hola, lo importante es que el output de las funciones sea el deseado, en este caso los nombres. Puedes modelarlo como quieras, pero recomiendo fuertemente que `Curso` guarde los ID en vez de nombres. Igual que en la vida real, dos personas pueden tener el mismo nombre, pero nunca compartirán el mismo ID
