### ISSUE TITLE
Comandos README.md

### ISSUE THREAD

**Issue by fabarros** [IIC2143-2019-2/proyecto#25]
Hola! quería saber si los comandos que están en el README son pensando la terminal de Linux o la de Windows, o sirven para ambos? En la ayudantía dijo el men que si se usa Linux hay que anteponer sudo (no es mi caso). Es la única diferencia?
Gracias, saludos.

**Comment by jerosalazar** [comment]
Hola, los comandos son los mismos tanto para windows, linux y Mac. Lo único que hay que agregar es anteponer `sudo` en caso de ser linux como comentaste

**Comment by daleal** [comment]
Hola! Quiero agregar que en Windows el comando `sudo chown -R $USER:$USER .` no es necesario y que probablemente arroje un error.
