### ISSUE TITLE
[Docker][Duda Rubocop]

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2143-2019-2/proyecto#28]
Hola!
Estaba avanzando en la parte de docker y me surgio una duda respecto al inciso que pide rubocop para la entrega 0. Mi duda es, ¿Para crear la configuración de rubocop en el contenedor de docker es necesario crear un archivo .rubocop.yml dentro de la carpeta de root, y en el escribir las restricciones?
Desde ya muchas gracias!.

**Comment by movaldivia** [comment]
Hola!

Como sale en la página rubocop ya viene con un default
![image](https://user-images.githubusercontent.com/24725124/64179326-fb37c900-ce30-11e9-8062-a5356fbc65a4.png)

**Aún así tu debes crear tus propias reglas (tu propio archivo), que tenga sentido**. Por ejemplo, no sirve que permitas 1000 caracteres por línea.

**Comment by arbiocanpion** [comment]
Muchas gracias!
