### ISSUE TITLE
[Tarea] - Duda con función top_n_notas()

### ISSUE THREAD

**Issue by jotanavarrete** [IIC2143-2019-2/proyecto#3]
Hola! Respecto a la función `top_n_notas()` que se nos pide implementar, creo que debería recibir algún _input_ para indicar cuántas mejores notas hay que encontrar. Por ejemplo, `top_n_notas(5)` debería escribir la lista con las cinco mejores notas.
Si es que no recibe _input_, ¿a qué se refiere con "n mejores notas"?

**Comment by jerosalazar** [comment]
Hola! Actualizamos el enunciado para que lo veas, ahí se explica que se pasa como input la linea `top_n_notas,numero_n` en el archivo csv_acciones. Espero que te sirva

**Comment by alexaptib** [comment]
@jerosalazar Viendo la nueva version del enunciado, se debe entregar las top n notas para todos los cursos? o bien, falta un parametro para definir de que curso se lo pide no?

**Comment by jerosalazar** [comment]
Revisando lo que dijiste me di cuenta de que hay un error. Efectivamente las top n notas son de un curso especifico. Por lo tanto el input del archivo debiese ser `top_n_notas,ID_Profesor,numero_n`. Cambiaré altiro el enunciado y el csv de acciones

**Comment by tpcantergiani** [comment]
Hola
No me quedo claro si se le debe entregar `numero_n` como input a la  funcion `top_n_notas()`
 (definir la función como:  `top_n_notas(numero_n)`).
Si este no es el caso, se podría hacer que la función entregue las notas ordenadas y después se escriban las n mejores notas? (en `ejecutar_programa` por ejemplo)

**Comment by vjaguilera** [comment]
Hola
Efectivamente el método `top_n_notas()` debiese utilizar como input a `numero_n` para retornar las `numero_n` mejores notas. La implementación del retorno del método queda a criterio personal, mientras cumpla lo solicitado por enunciado (leer bien qué método es el que escribe en el archivo de output).

**Comment by GbPoblete** [comment]
Si la función top_n_notas entrega un n que es mayor a la cantidad de notas del curso, imprimo todas las notas de ese curso o ***ERROR EN LA CONSULTA** ??  Gracias!

**Comment by atbusch** [comment]
@GbPoblete no tienes que preocuparte de ese caso, no va a pasar cuando se revise la tarea.
