### ISSUE TITLE
Error "ownership data directory" en windows

### ISSUE THREAD

**Issue by ghost** [IIC2143-2019-2/proyecto#30]
Hola!

Estoy intentando levantar la aplicación en mi pc pero al poner `docker-compose up` me aparece este error  (estoy ocupando toolbox)

![image](https://user-images.githubusercontent.com/48300995/64198001-65626500-ce55-11e9-81f4-ec9a4f9a1a5a.png)

La aplicación la hicimos en otro computador con linux, asi que yo solo cloné los archivos y ejecuté los últimos comandos que salían en el README.

**Comment by daleal** [comment]
Hola! Podrías mandarme el contenido de tu `docker-compose.yml` y el contenido de tu `config/database.yml`?

**Comment by ghost** [comment]
`docker-compose.yml`
![image](https://user-images.githubusercontent.com/48300995/64278488-de77c000-cf1a-11e9-9465-f60bfa5d5b0f.png)
`config/database.yml`
![image](https://user-images.githubusercontent.com/48300995/64278567-08c97d80-cf1b-11e9-913c-c2161af06839.png)

**Comment by dedarritchon** [comment]
Me pasa lo mismo, supongo que es porque no hacemos lo equivalente a sudo chown -R $USER:$USER . en windows:
al correr:
>docker-compose run web rails db:create
Starting my_app_db_1 ... done                    
could not translate host name "db" to address: Name or service not known
Couldn't create 'my_app_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not translate host name "db" to address: Name or service not known

luego al correr:
>docker-compose up
Starting my_app_db_1 ... done
Creating my_app_web_1 ... done
Attaching to my_app_db_1, my_app_web_1
...
db_1   | running bootstrap script ... 2019-09-05 16:29:01.673 UTC [77] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
db_1   | 2019-09-05 16:29:01.673 UTC [77] HINT:  The server must be started by the user that owns the data directory.
db_1   | child process exited with exit code 1
db_1   | initdb: removing contents of data directory "/var/lib/postgresql/data"
my_app_db_1 exited with code 1

los archivos:
`docker-compose.yml`
![image](https://user-images.githubusercontent.com/17625557/64361344-59ec7680-cfda-11e9-8d00-842abb317b38.png)
`config/database.yml`
![image](https://user-images.githubusercontent.com/17625557/64361373-68d32900-cfda-11e9-97a3-c026aa879c33.png)

**Comment by daleal** [comment]
Están usando Toolbox para correr Docker?

**Comment by dedarritchon** [comment]
No yo Docker Desktop que es lo que salía en el link del readme

**Comment by vjaguilera** [comment]
Hola @javieraochoa @dedarritchon, quizás el asunto está en que el nombre es case sensitive. Prueben con "orsini" y "myapp" (en vez de Orsini y my_app).

**Comment by dedarritchon** [comment]
> Hola @javieraochoa @dedarritchon, quizás el asunto está en que el nombre es case sensitive. Prueben con "orsini" y "myapp" (en vez de Orsini y my_app).

probe con "myapp" y paso lo mismo de antes

**Comment by daleal** [comment]
Luego de investigar un poco esta situación, aparentemente ocurre debido a que el volumen creado es de propiedad de Docker. Además, aparentemente esto **no** ocurre cuando se trata de levantar el servicio usando **Docker Toolbox**. Lo que yo haría sería:

1. Intentar abrir una consola con derechos de administrador y de ahí ejecutar los comandos
2. Si eso no funciona, instalaría Docker Toolbox y ejecutaría todo desde ahí

Lamento no poder darles una respuesta más concreta que esto :disappointed: pero creo que con alguno de los dos pasos anteriores lograrán levantar su app.

**Comment by ghost** [comment]
Yo estoy ocupando Docker Toolbox y no 😢 intenté también hacer lo de la consola pero también me sale el mismo error

**Comment by dedarritchon** [comment]
Al final instalé Ubuntu y funcionó
