### ISSUE TITLE
Tipo de usuario restaurante

### ISSUE THREAD

**Issue by ararojas** [IIC2143-2019-2/proyecto#33]
Hola!
En el enunciado del proyecto nos dicen los 3 tipos de usuarios que deben existir, en los cuales no existe un usuario restaurante. Por otro lado, muchas de las funcionalidades van dirigidas a los restaurantes. ¿Podemos agregar un nuevo tipo de usuario? ¿O debemos considerar los restaurantes como clientes normales que tienen restaurantes?
Saludos,
Araceli

**Comment by dagalloso** [comment]
Hola! Pueden hacerlo de ambas formas, en ese sentido les dejamos la libertad de modelación. Es importante que vean qué implica cada caso y que, en base a eso, tomen una decisión.
Saludos!
