### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by AgustinErrazuriz** [IIC2143-2019-2/proyecto#34]
Hola!! Cuál es un buen editor de texto para Ruby?

**Comment by atbusch** [comment]
Hola! Yo recomiendo mucho Atom o Sublime. Funcionan bien con cualquier lenguaje, no solo ruby.

**Comment by vjaguilera** [comment]
Hola, Visual Studio Code también es una buena opción. Hay mucho material en internet para desarrollar RoR de la mejor manera con este editor de texto!
