### ISSUE TITLE
[Tarea] Duda con archivo acciones

### ISSUE THREAD

**Issue by pablovejar** [IIC2143-2019-2/proyecto#35]
**Hola!** 
Me surgió la duda de si está correcto que en el archivo de acciones en vez de la sigla del curso, nos pasen la sigla del profesor para las consultas que involucran métodos que están dentro de la clase Curso, o simplemente tengo que lanzar error en la consulta :hushed: . Saludos!  :v:

**Comment by quememo** [comment]
creo que está bien, pero muy mal modelado como parte de la tarea

**Comment by vjaguilera** [comment]
Hola @pablovejar, efectivamente está correcto el formato de esas consultas, y para aclararle las dudas a @quememo, no debiese existir ningún problema si **su modelación** es correcta (recuerden que Curso y Profe es 1-1).
Saludos.
