### ISSUE TITLE
[Tarea] archivo acciones

### ISSUE THREAD

**Issue by isavega** [IIC2143-2019-2/proyecto#36]
Hola!

No entiendo si lo que aparece en este archivo son ejemplos de consultas o es un archivo que debemos trabajar para que se realicen esas consultas automáticamente. 

Hice mi tarea pensando en interactuar con la consola, por ejemplo:

![image](https://user-images.githubusercontent.com/42187168/64225556-e2b7c500-cea9-11e9-97ad-618c34ab4437.png)

Todas las consultas me funcionan pero no sé si lo que hice es válido, gracias 😄

**Comment by mvgil** [comment]
Hola! 
La idea es que dado el csv de acciones, imprimas en el archivo output.txt lo que retorna cada consulta. No hay que interactuar con la consola, solo escribir en el `output.txt`
