### ISSUE TITLE
[Tarea] output cursos_reprobados

### ISSUE THREAD

**Issue by nep0s** [IIC2143-2019-2/proyecto#37]
Hola, en el enunciado dice que el output para la función cursos_reprobados de Alumno tiene que estar en el formato `Cursos aprobados por {id alumno}: [lista con siglas de cursos reprobados]`

¿No debiera decir en cambio `Cursos reprobados por {id alumno}: [lista con siglas de cursos reprobados]`?

Gracias de antemano.

**Comment by mvgil** [comment]
Hola!
Sí, hubo un error de tipeo, pero se debería imprimir: 
``Cursos reprobados por {id alumno}: [lista con siglas de cursos reprobados]``
