### ISSUE TITLE
[Tarea] - No me deja escribir con un string a un archivo

### ISSUE THREAD

**Issue by Cadagan** [IIC2143-2019-2/proyecto#40]
Tengo todo hecho, pero al pasar el string que contiene la solucion (con un salto de linea al terminar la respuesta de cada consulta), me dice

"tarea.rb:559:in `initialize': no implicit conversion of Hash into String (TypeError)"

y el texto no es de tipo hash por ningun lado (lo comprobe con "respuesta.class" y me arroja string)

Alguien sabe que podría ser? de antemano muchas gracias :)

**Comment by jerosalazar** [comment]
Hola! que es lo que estas tratando de escribir? si estas trabajando con una diccionario (por ejemplo) podrías estar teniendo algún error [así](https://stackoverflow.com/questions/27372255/ruby-typeerror-no-implicit-conversion-of-hash-into-string)

**Comment by Cadagan** [comment]
Finalmente descubri que parece que toque un metodo de ruby para pasar un string a hash. Por si a alguien le pasa lo mismo, simplemente le puse otro nombre al metodo y funciono todo perfecto :)
