### ISSUE TITLE
[Tarea] -Problema ID alumnos en "cvs_profesores.csv"

### ISSUE THREAD

**Issue by rsnegrin** [IIC2143-2019-2/proyecto#41]
Hola !
Los siguentes id_alumnos están en el curso de algún profesor, pero no es encuentran en el archivo _"csv_alumnos.csv"_.
id_alumnos:

5239
1767
5239
5239
5239
1767

¿Debo considerarlos como alumnos? No tendrían nombre, edad, etc 
O simplemente los descarto cuando leo los alumnos que es encuentran en un curso.

Gracias!

**Comment by jerosalazar** [comment]
Hola! revisa la issue #6 😊
