### ISSUE TITLE
[Tarea 1] Modelación error_csv

### ISSUE THREAD

**Issue by cjones27** [IIC2143-2019-2/proyecto#42]
Hola!

Con respecto a la función error_csv, me complica el hecho de tener que crear una función que maneje los errores de todas las funciones siendo que el manejo de errores para los inputs es normalmente dentro de cada función (por lo menos así lo aprendi yo en programación avanzada).

Es esta modelación obligatoria o si se cumple la misma funcionalidad con otra modelación esta será correcta?

Muchas gracias!

**Comment by vjaguilera** [comment]
Hola, el objetivo se la función error es precisamente analizar el input de acciones que le entregaremos y escribir en _output.txt_ la presencia del error. Es como un filtro del input de acciones, que si pasa correctamente, gatilla los métodos solicitados. Ahora, el método error puedes utilizarlo en el lugar que quieras, mientras cumpla con los requisitos del enunciado (escribir en el output la presencia del error).

**Comment by cjones27** [comment]
Yap, gracias! 😁
