### ISSUE TITLE
[Proyecto] Scope de RuboCop

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2143-2019-2/proyecto#43]
A lo largo de las entregas, va a ser necesario que RuboCop nos detecte 0 errores solo en el _folder_ `app` o en todo el folder de la applicación (Inlcuidos dockerfile, configs, db, etc etc)?

Gracias!

**Comment by jerosalazar** [comment]
Hola! las exigencias de rubocop deben conversarlas más en detalle con sus _product owner_. Al final ellos serán quienes revisarán eso 😊
