### ISSUE TITLE
[Tarea 1] Aclaración función cantidad_alumnos_sin_reprobar_ramos

### ISSUE THREAD

**Issue by cjones27** [IIC2143-2019-2/proyecto#44]
Hola! 

En la función cantidad_alumnos_sin_reprobar_ramos dice que el output es {cantidad}: [alumno1, alumno2, ...] pero no se especifica si alumnoX es el id del alumnoX o su nombre.

gracias!

**Comment by jerosalazar** [comment]
Hola! deben ir los nombres de los alumnos 😊
