### ISSUE TITLE
Instalación Docker

### ISSUE THREAD

**Issue by fabarros** [IIC2143-2019-2/proyecto#45]
Hola! 
Tengo un problema cuando trato de instalar Docker con el comando en Ubuntu. Cuando pongo lo siguiente: 
`sudo apt-get install docker-ce docker-ce-cli containerd.io`
me dice:
```
El paquete docker-ce no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «docker-ce» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete docker-ce-cli
E: No se ha podido localizar el paquete containerd.io
E: No se pudo encontrar ningún paquete usando «*» con «containerd.io»
E: No se pudo encontrar ningún paquete con la expresión regular «containerd.io»
```
Gracias! Saludos.

**Comment by jerosalazar** [comment]
Hola! puedes seguir [este tutorial](https://phoenixnap.com/kb/how-to-install-docker-on-ubuntu-18-04) que (a mi juicio) es un poco más fácil que lo que sale en la página oficial

**Comment by fabarros** [comment]
Hola, gracias!
Pude unstalar Docker (creo) pero ahora tengo problemas para instalar Ruby :( en particular, para instalarlo primero debo actualizar con `sudo apt update`, pero cuando lo hago me salen varios errores de este estilo: 
```
E: El archivo de lanzamiento para http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease aún no es válido (no válido para otro 5h 53min 13s). Las actualizaciones para este repositorio no se aplicarán.
```
Asumo que no poder actualizar bien me causa problemas para instalar Ruby, dehecho cuando intento instalar Ruby con `sudo apt install ruby-full` me dice que hay algunos archivos que no se pudieron instalar y que pruebe usando `sudo apt update` y cuando trato de ejecutar algún comando de ruby no lo reconoce.
Qué puede ser? debo esperar las 6 hrs xd?
Gracias, estoy aprendiendo esta cuestión de la terminal.

**Comment by jerosalazar** [comment]
Como explicamos en la ayudantía no es necesario que instales ninguna versión de ruby o de rails en tu computador, ya que para eso está docker

**Comment by CmPoblete** [comment]
Al hacer docker-compose build se ejecutara un comando que instalara ruby y rails en docker

**Comment by fabarros** [comment]
Bacán, gracias. 
Ahora estoy tratando de crear la aplicación de Rails con el `docker-compose run web rails new . --force --no-deps --database=postgresql` pero al final me tira el siguiente error
```
Step 2/17 : RUN apt-get update &&    apt-get install -y locales &&    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen &&    rm -rf /var/lib/apt/lists/*
 ---> Running in 156a93150610
Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales' has no installation candidate
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update &&    apt-get install -y locales &&    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen &&    rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
Pienso que puede seguir siendo el rollo de `sudo apt-get update` pero en verdad no cacho :/
Gracias por la ayuda cabros.
