### ISSUE TITLE
[proyecto][rails]

### ISSUE THREAD

**Issue by matumartinez** [IIC2143-2019-2/proyecto#46]
Hola

Cuando creo una nueva aplicación con rails (rails new myapp) e intento hacer alguna acción con rails, me da el siguiente error:

Could not find gem 'pg (>= 0.18, < 2.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

Sin embargo, cuando corro bundle install, me dice esto:

An error occurred while installing pg (1.1.4), and Bundler cannot
continue.
Make sure that `gem install pg -v '1.1.4' --source 'https://rubygems.org/'`
succeeds before bundling.

Cuando intento hacer `gem install pg -v '1.1.4' me da otro error en que dice que use "bundle install".

He buscado soluciones en internet y nada ha servido (estoy intentando hacer la parte del proyecto semestral relacionada con Heroku).

Gracias de antemano

**Comment by jerosalazar** [comment]
Hola! Hiciste `docker-compose build` luego de crear la app? Recuerda que cualquier comando que corras (de rails, bundle, etc) debes anteponerle `docker-compose run web` y que `docker-compose build` corre (entre otras cosas) bundle install
