### ISSUE TITLE
Problemas con el comando docker-compose up 

### ISSUE THREAD

**Issue by t-schilling** [IIC2143-2019-2/proyecto#48]
Hola, siguiendo los pasos de la ayudantía del viernes pasado me funcionó todo perfecto, pero al realizar el último comando  "sudo docker-compose up" (estoy usando linux) en la consola no me para de aparecer el siguiente error. Busqué en internet y no pude encontrar alguna solución.
Gracias!
![Captura de pantalla de 2019-09-04 22-26-10](https://user-images.githubusercontent.com/48298905/64307125-228eb300-cf63-11e9-845f-bfe6cacc2cd9.png)

**Comment by vtespinosa** [comment]
Hola, corre el comando sudo chown - R $USER:$USER con la terminal abierta para todo el computador y no solo en tu repositorio.

**Comment by t-schilling** [comment]
Hola, abrí la terminal en el escritorio y fui haciendo "cd .." hasta llegar al princípio y ahí corrí el comando "sudo chown - R $USER:$USER" el problema es que después al correr "sudo docker-compose up" en mi repositorio me aparece el error "sudo: /usr/bin/sudo debe ser propiedad del uid 0 y tener el bit setuid establecido".
Ahora no puedo correr nada con el comando sudo ni conectarme a internet

**Comment by daleal** [comment]
Esta issue es un duplicado de la issue #12
