### ISSUE TITLE
[Proyecto] - Problema docker-compose

### ISSUE THREAD

**Issue by colorostrobl** [IIC2143-2019-2/proyecto#49]
Hola, he estado tratando de seguir los pasos en el README, pero al _ejecutar docker-compose run web rails db:create_ me aparece el siguiente error (estoy trabajando en MacOS):
/usr/local/bin/docker-compose: line 1: syntax error near unexpected token `<'
/usr/local/bin/docker-compose: line 1: `<!DOCTYPE html><title>Malformed request<'title>
Trate de correr otros comandos en docker compose pero siempre me aparece el mismo error.

**Comment by daleal** [comment]
Hola! Podrías enviar el contenido de tu `docker-compose.yml`?

**Comment by colorostrobl** [comment]
![Captura de pantalla 2019-09-06 a la(s) 10 25 02](https://user-images.githubusercontent.com/42244060/64435637-d6da2780-d090-11e9-8822-78b39e3e3d00.png)
