### ISSUE TITLE
PRoblema siguiendo pasos Example

### ISSUE THREAD

**Issue by ftrejoc** [IIC2143-2019-2/proyecto#51]
Hola!
Estaba siguiendo los pasos del example y al momento de correr sudo docker-compose run web rails new . --force --no-deps --database=postgresql
Me aparece el siguiente error:

mkdir: invalid option -- 'c'
Try 'mkdir --help' for more information.
ERROR: Service 'web' failed to build: The command '/bin/sh -c mkdir $docker-compose.yml' returned a non-zero code: 1
Qué tengo que hacer para solucionarlo?
Muchas gracias!

**Comment by daleal** [comment]
Hola! Parece ser que sin querer ejecutaste el comando `sudo docker-compose run web rails new . --force --no-deps --database=postgresql c` en vez de ejecutar `sudo docker-compose run web rails new . --force --no-deps --database=postgresql` (solamente basado en el error que aparece). Revisa si no apretaste la `c` sin querer justo antes de ejecutar el comando
