### ISSUE TITLE
Problema haciendo deploy a heroku

### ISSUE THREAD

**Issue by Dunkan1** [IIC2143-2019-2/proyecto#52]
Cuando hice git push heroku master, me aparecio el siguiente error:

![Screenshot from 2019-09-05 19-58-57](https://user-images.githubusercontent.com/26102365/64391754-e6695a00-d017-11e9-839c-65424468b8d3.png)

aun asi en heroku aparece como "Build succeeded", pero cuando abro la pagina aparece esto

![Screenshot from 2019-09-05 20-04-19](https://user-images.githubusercontent.com/26102365/64391874-61327500-d018-11e9-99fa-7e4f943fd819.png)

**Comment by daleal** [comment]
Hola! El problema es que no estás deployeando tu app en Heroku usando Docker, sino que la estás deployeando como si fuera una app de rails cualquiera. Te recomiendo [esta guía](https://devcenter.heroku.com/articles/container-registry-and-runtime) para poder hacer deploy de tu app a Heroku usando tu imágen de Docker (ten en cuenta que en tu app de Heroku **debes** instalar el _add-on_ de postgres para que todo funcione).

**Comment by Dunkan1** [comment]
gracias, intente seguir la guia y agregue el add-on de postgres a la app, pero cuando hago 
``` heroku container:push web ```
obtengo el siguiente error
```
=== Building web (/home/mrf/Documents/2019-2/Ingenieria-Soft/Grupo27-proyecto/AppWeb/Dockerfile)
error checking context: 'can't stat '/home/mrf/Documents/2019-2/Ingenieria-Soft/Grupo27-proyecto/AppWeb/tmp/db''.
 ▸    Error: docker build exited with Error: 1

```

**Comment by daleal** [comment]
Si estás en linux, tienes que ejecutar `sudo heroku container:push web` y `sudo heroku container:release web`

**Comment by Dunkan1** [comment]
buena lo logre, los comandos que use fueron
```
heroku login
git init
git add .
git commit -m "init added"
heroku create
heroku container:push web
heroku container:release web
```
luego añadi el add-on de postgres que dijiste (desde la pagina de heroku) a la app
y po ultimo hice
```
heroku open
```
