### ISSUE TITLE
Error de conexión con Rails

### ISSUE THREAD

**Issue by jjzapatai** [IIC2143-2019-2/proyecto#53]
Llevo desde ayer intentando de hacer el ejemplo y me sale el siguiente error al crear la base de datos. Porfa ayuda!

rails aborted!
YAML syntax error occurred while parsing /jjz39/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected key while parsing a block mapping at line 10 column 3

![Screenshot_2](https://user-images.githubusercontent.com/48264167/64395416-318b6900-d028-11e9-941f-069455a06c90.png)

**Comment by daleal** [comment]
Hola! Podrías mandar el contenido de tu archivo `config/database.yml`?

**Comment by jjzapatai** [comment]
Aca lo envío:

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: {jjz39}_development


test:
  <<: *default
  database: {jjz39}_test

**Comment by mimunoz11** [comment]
Creo que debes poner:

default: &default
adapter: postgresql
encoding: unicode
host: db
username: postgres
password:
pool: 5

development:
<<: *default
database: jjz39_development

test:
<<: *default
database: jjz39_test
