### ISSUE TITLE
Problema Heroku

### ISSUE THREAD

**Issue by fabarros** [IIC2143-2019-2/proyecto#54]
Hola! mi Hello World funciona en el localhost:3000, pero al pasarlo a Heroku me aparece un error. Hice `sudo heroku container:push web` y `sudo heroku container:release web` y ambos se pudieron ejecutar bien. Pero cuando entro a la página de Heroku me sale lo siguiente:
![Captura de pantalla de 2019-09-06 01-04-41](https://user-images.githubusercontent.com/30666832/64402331-8b009180-d042-11e9-91f5-eea21cdc2136.png)
Qué puedo hacer?
Gracias!

**Comment by CmPoblete** [comment]
Hola, le agregaste el addon de postgres en heroku?

**Comment by fabarros** [comment]
Lo hice y ahora me surge otro problema, no me deja hacer push a Heroku, me dice que necesita auntentificación pero ya me logié en Heroku :/ 
Encontré que le pasaba a personas que no estaban logeadas en Docker, me logié en Docker y nada tampoco, y ya corrí el comando para darme acceso a los archivos (Ubuntu).
Gracias por la ayuda.

**Comment by Dunkan1** [comment]
hiciste heroku push web o heroku container:push web?

**Comment by fabarros** [comment]
Antes, podía hacer push. Cuando terminó el Push fue que revisé la página y me salió ese error en Rojo. Ahora empieza en Push y se detiene por `autentication requiered`

**Comment by Dunkan1** [comment]
Si tu no hiciste lo del docker y clonaste el repo y ahora lo intentas subir a heroku debes hacer lo que aparece en el readme de examples, lo de sudo chmod $user......., eso quizas lo arregle

**Comment by daleal** [comment]
Hola! El flujo de comandos para subir las cosas a Heroku **usando docker** es el siguiente:

- `heroku container:login` (introducir las credenciales de Heroku luego de esto)
- `heroku container:push web`
- `heroku container:release web`

En caso de estar usando Linux, anteponer `sudo` a todos los comandos. Si ya agregaron el _add-on_ de postgres a su app de Heroku, con esos comandos la app debería quedar funcionando

**Comment by fabarros** [comment]
Funcionando! Gracias. El problema era:
1. No había hecho `addons` de postgresql en Heroku
2. Al logear en Heroku estaba haciendo `sudo heroku login` en vez de `sudo heroku container:login`
Lo dejo por si a alguien más le pasa. Gracias, saludos.
