### ISSUE TITLE
[Windows 10] - Crear base de datos

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2143-2019-2/proyecto#55]
Hola! al correr el comando `docker-compose run web rails db:create` en `Docker Desktop for Windows 10` me arroja el siguiente error
```
could not translate host name "db" to address: Name or service not known
Couldn't create 'example_development' database. Please check your configuration.
rails aborted!
```

A mis compañeros en `Linux` y `MacOS` les funciona.
¿Qué hago? :(

**Comment by quememo** [comment]
creo que el ejemplo no funciona en windows 10 simplemente, me parece está diseñado para funcionar en los otros sistemas operativos desde un comienzo

encontré esto que si sirve en windows 10 y se parece bastante al ejemplo que está subido
https://medium.com/@adrianlpad/gu%C3%ADa-instalar-rails-5-con-docker-windows-linux-mac-75d2c344fc41

**Comment by VicenteVicente** [comment]
Gracias, lo revisaré luego y te cuento qué tal!

**Comment by jerosalazar** [comment]
Hola! Pudiste solucionar el error?

**Comment by VicenteVicente** [comment]
No he podido:( he intentado de todo

**Comment by jpgonzalez4** [comment]
Intenta con docker-compose run web **rake** db:create

**Comment by VicenteVicente** [comment]
Con ``` docker-compose run web rake db:create```, arroja el error:
```standard_init_linux.go:211: exec user process caused "no such file or directory"```
