### ISSUE TITLE
[Docker] Crear app de rails no funciona

### ISSUE THREAD

**Issue by Cadagan** [IIC2143-2019-2/proyecto#57]
Llevamos horas con el mismo error al correr el comando "docker-compose run web rails new . --force --no-deps --database=postgresql", que es:

```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

Docker si est corriendo, ya que ocupamos el comando "sudo systemctl enable docker", con output de

```
 "Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
"
```

Ayuda por favor :( estamos desde una maquina virtual ubuntu 18.04, con rails version 4.2.0, ruby 2.5

**Comment by movaldivia** [comment]
@Cadagan intenta con `sudo docker-compose run web rails new . --force --no-deps --database=postgresql` sino funciona avisa
