### ISSUE TITLE
[Heroku] Actualizar cambios

### ISSUE THREAD

**Issue by Franco1605** [IIC2143-2019-2/proyecto#58]
Hola,
Había subido la app a heroku, per ahora implementé unos cambios en los archivos. Cuando intento subirla de nuevo, me aparece este error:

! [remote rejected] master -> master (pre-receive hook declined)
error: falló el push de algunas referencias a 'https://git.heroku.com/aqueous-chamber-64582.git'
¿Qué debo hacer?

**Comment by jerosalazar** [comment]
Hola, puede ser que versiones distintas en tu repo local y el de heroku (como cuando otro usuario hace push de algunos cambios y tu intentas pushear otros sin agregar los de tu compañero). [Acá](https://stackoverflow.com/questions/9794413/failed-to-push-some-refs-to-githeroku-com) pueden haber datos que te sirvan
