### ISSUE TITLE
[Proyecto] No funciona hacer push al repositorio privado

### ISSUE THREAD

**Issue by dberezin** [IIC2143-2019-2/proyecto#59]
Hola,

Subí el hello world al heroku y ahora estoy intentando subir la misma carpeta al github privado para que lo puedan revisar. Cloné el repositorio vacío y copié la carpeta del proyecto, pero al intentar hacer push (ya sea con 'git push' o 'git push -u origin master') recibo la respuesta 

`remote: Repository not found.`
`fatal: repository 'https://github.com/IIC2143-2019-2/Grupo04-proyecto/' not found`
Como se puede solucionar? 
Puede que sea un problema con los permisos sobre el repo privado?

**Comment by mjgarrido1** [comment]
hola! tienes que inicializar la repo. Si te metes por github y clickeas tu repo privado te saldran las instrucciones para hacerlo

**Comment by jerosalazar** [comment]
Hola, reviré y lo que pasaba es que tu grupo tenía permiso de read en vez de write para el repo. Ya lo arreglé, así que están listos.

Si a algun otro grupo le pasa lo mismo, avíseme para arreglarlo!

**Comment by dberezin** [comment]
Ahora sí se pudo, gracias!
