### ISSUE TITLE
[Tarea] - Manejo de alumnos inexistentes

### ISSUE THREAD

**Issue by Banfanci** [IIC2143-2019-2/proyecto#6]
Probando mi programa me di cuenta que al cargar las bases de datos hay alumnos dentro de la parte de notas de los alumnos del archivo csv de los profesores que no existen dentro del csv de alumnos, en particular encontré el alumno con id "5239". Nuestro programa debiese manejar estos casos o es un error de las bases de datos subidas??

**Comment by jerosalazar** [comment]
Revisando bien me di cuenta de que las ultimas 2 filas de alumnos no se escribieron en el csv de alumno, por lo que dentro del csv de profesores deben haber 2 alumnos cuya información no se encuentra. Actualizaré el csv de alumnos para que estén, pero en la corrección real esto va a estar arreglado, por lo que **no deben preocuparse de que aparezcan ids de alumnos cuya información no se encuentre en el csv correspondiente**

**Comment by KnowYourselves** [comment]
Hola @jerosalazar!

Todavía no actualizas el csv de alumnos?, Me está pasando el mismo error. (De momento elimina a mano los datos conflictivos :eyes: )

**Comment by jerosalazar** [comment]
Acabo de cachar que no se publicó mi ultima respuesta 😢 Había escrito que no actualicé el csv, pero que pueden agregar los alumnos a mano si quieren. Lo importante es que en la revisión este tipo de error no pasará
