### ISSUE TITLE
[Docker] Error: did not find expected key while parsing a block mapping at line 10 column 5 

### ISSUE THREAD

**Issue by figarcia3** [IIC2143-2019-2/proyecto#60]
Hola intentando abrir rails en docker ocurre este error en el archivo de /config/database.yml Tengo esto en el database.yml 
![Captura de pantalla de 2019-09-07 15-31-37](https://user-images.githubusercontent.com/48328327/64479407-c99e6500-d184-11e9-9381-ef982d3680e7.png)

**Comment by jerosalazar** [comment]
Hola! Tienes que sacar los corchetes en los nombres de las bdd

**Comment by figarcia3** [comment]
Gracias
