### ISSUE TITLE
Ayudantía 3 (viernes 6 de septiembre)

### ISSUE THREAD

**Issue by cristianoberpaur** [IIC2143-2019-2/proyecto#61]
Quería saber si van a subir algún documento sobre los commandos utilizados en esta ayudantía ya que no alcance a anotralos todos. O si van a subir algo relacionado a esta ayudantía. 
Se que este es el repositorio del proyecto, pero el foro del siding no se esta usando mucho =).

**Comment by jerosalazar** [comment]
Hola! Cualquier duda sobre las ayudantías pueden preguntarlas por acá. No hay problema.

Lamentablemente no subiremos los códigos ocupados en la ayudantía para instarlos a que asistan a ella.

Saludos
