### ISSUE TITLE
Error al crear la base de datos

### ISSUE THREAD

**Issue by PabloLorca23** [IIC2143-2019-2/proyecto#62]
Hola, 
![Captura de pantalla de 2019-09-11 11-44-35](https://user-images.githubusercontent.com/48296565/64707592-9829e000-d489-11e9-8ec5-60865455e967.png)

Cuando creo una app desde mi computador funciona todo bien, pero si trato de correr una creada desde otro computador me sale un error al crear la base de datos, ya trate con los comandos docker-compose up y down y no se arregla. Mi compañero que creo la app si la puede correr en su computador

**Comment by jerosalazar** [comment]
Puedes mostrarme como está su config database?

**Comment by daleal** [comment]
Aprovecha de enviar, aparte de tu `config/database.yml`, tu `Dockerfile` y tu `docker-compose.yml`. Qué sistema operativo tiene cada integrante del grupo?
