### ISSUE TITLE
Windows 10- Error al correr docker-compose run web rails new . --force --no-deps --database=postgresql

### ISSUE THREAD

**Issue by fivaldivia** [IIC2143-2019-2/proyecto#64]
Hola, al correr el comando descrito me tira el siguiente error: standard_init_linux.go:211: exec user process caused "no such file or directory". Trate cambiando los port a 8000 pero no me sirve. He googleado pero salen muchas soluciones distintas las cuales algunas las probe y no me sirvieron. Estoy usando  Docker desktop for Windows. Encontré esta página (http://www.devops-blog.net/docker/advice-on-building-docker-images-on-windows) que siento que me podría servir pero no entiendo la solucion que dan, si alguien me puede ayudar, ya que no se qué más hacer muchas gracias.

**Comment by daleal** [comment]
Hola! Aparentemente (por lo menos según lo que dicen en esa página) el error se da debido a que git cambia los `\n` que se usan en linux a los `\r\n` que se usan en Windows, pero el `entrypoint.sh` es un archivo`.sh` que la máquina virtual de docker ejecuta. Pero como esa máquina es linux, los saltos de línea (que deberían ser `n`) se transforman en `\r\n`, haciendo que el script sea imposible de ejecutar y tire el error.  La solución que dan es añadir a tu repo un archivo llamado `.gitattributes` con el siguiente contenido:

```txt
# Auto detect text files and perform LF normalization
* text=auto

# dont touch bash scripts so it doesnt mess up the shebang #!/bin/bash
*.sh text eol=lf
```

Lo que hace ese archivo es decirle a git que cambie los cambios de línea de `\n` a `\r\n` solamente en archivos que no terminen en `.sh` para que así el `entrypoint.sh` no se vea modificado y pueda ser ejecutado por la máquina virtual de docker. Hazlo y dime cómo te va!

**Comment by fivaldivia** [comment]
Hola, lamentablemente me sigue saliendo e mismo error:
![image](https://user-images.githubusercontent.com/42453679/64882300-35744800-d633-11e9-8f91-b3ed886fab75.png)
Solo me crea la carpeta "tmp".

**Comment by daleal** [comment]
Intenta cambiar los finales de línea del `entrypoint.sh` desde tu editor de texto. En vscode, en la barra de estado de abajo debería haber un botón que dice `CRLF`. Aprétalo y cambia su valor a `LF` (en otros editores de texto debe ser algo similar, pero la idea es cambiar las terminaciones de línea de tu `entrypoint.sh` de `CRLF` a `LF`). Luego intenta crear la app de nuevo y dime qué tal.

**Comment by fivaldivia** [comment]
Lo hice y me sale el mismo error :(. Instale subsystem y talvez se mezclo con el otro. Te dejo foto de lo que me sale si hago docker-compose up luego de tratar de crear la base, al parecer es un problema de permisos.
![WhatsApp Image 2019-09-14 at 00 24 52](https://user-images.githubusercontent.com/42453679/64902910-9ed17680-d686-11e9-9afb-8a58718e57bc.jpeg)

**Comment by daleal** [comment]
Hola! El problema que me muestras es distinto al original y tiene que ver con la issue #63, por lo que cierro esta issue. Cualquier duda con ese error, síguelo en la otra issue.
