### ISSUE TITLE
Problema en la migración 

### ISSUE THREAD

**Issue by Michelmagna** [IIC2143-2019-2/proyecto#66]
Hola!

Esto aprendiendo a usar rails y docker, siguiendo tutoriales para crear aplicaciones. Ocurre que  con 2 tutoriales siempre tengo el mismo problema: La migración. Esto creo que no lo hemos visto aún en ayudantías, pero al momento de migrar y seguir paso a paso el tutorial, me arroja siempre el siguiente error.

No sé si será error en el comando a ejecutar, pero si me ayudasen seria de mucha utilidad.

Gracias!

<img width="955" alt="Captura de Pantalla 2019-09-16 a la(s) 11 10 48 a  m" src="https://user-images.githubusercontent.com/40605397/64965266-106e1800-d873-11e9-9be8-b2cb214d4142.png">

**Comment by nissimergas** [comment]
no deberías usar rails db:migrate?

**Comment by CmPoblete** [comment]
Y para poder correrlo en Docker debes usar docker-compose run web rails db:migrate

**Comment by vjaguilera** [comment]
El comando completo debería incluir docker para ejecutarse correctamente.
Para correr las migraciones: docker-compose run web rails db:migrate
Para crear migraciones: docker-compose run web rails g migration <nombremigracion> <parámetros>

**Comment by Michelmagna** [comment]
@vjaguilera  Gracias crack <3  era un tema de comandos nada mas

**Comment by dmelberg** [comment]
> El comando completo debería incluir docker para ejecutarse correctamente.
> Para correr las migraciones: docker-compose run web rails db:migrate
> Para crear migraciones: docker-compose run web rails g migration <parámetros>

@vjaguilera pero si es el primer scaffold que hago, y no hay otras entidades creadas, solo User, deberia crear una migracion igual? me tira el mismo error de rails aborted al hacer 
`docker-compose run web rails db: migrate`

**Comment by CmPoblete** [comment]
@dmelberg El comando es docker-compose run web rails db:migrate sin espacio entre db: y migrate

Edit: al hacer el primer scaffold igual debes correr las migraciones porque estás creando una entidad y por lo tanto debes crear una tabla en la base de datos para esa entidad

**Comment by dmelberg** [comment]
@CmPoblete gracias!
