### ISSUE TITLE
Error al instalar devise

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2143-2019-2/proyecto#67]
Hola, al tratar de instalar la gema devise me sale el siguiente error

![Captura de pantalla de 2019-09-22 19-40-51](https://user-images.githubusercontent.com/47841749/65395428-01a2cc00-dd71-11e9-9014-b6ed20a66525.png)
He tratado de buscar en internet, pero no se me ocurre cuál puede ser el error, no se si me podrían ayudar

Saludos

**Comment by CmPoblete** [comment]
Como lo estas instalando?

**Comment by VicenteMerino** [comment]
Usando bundle install, me dijeron que ese error se daba porque como estamos usando el ambiente virtual de docker-compose, solo tengo que hacer docker-compose build, esto es así?

**Comment by CmPoblete** [comment]
Eso debes hacer. Al hacer bundle instaló estás instalando las gemas en tu computador, pero como están trabajando con Docker, debes instalarlas en tu ambiente virtual y eso se hace ejecutando docker-compose build.
