### ISSUE TITLE
Error con docker 

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2143-2019-2/proyecto#68]
Hola tengo un problema al instalar la app de rails a traves de dockers(?) estoy siguiendo el tutorial y comandos pero me aparecio lo siguiente:

![Captura de pantalla de 2019-09-22 22-02-01](https://user-images.githubusercontent.com/37159294/65397439-89df9c00-dd86-11e9-834a-84e7879b7fa5.png)

al principio me pedia la version 2.6 actualice pero me pidio la 2.5.1, 
cambie el gemfile (lo unico que hice) para que me pidiera la 2.6 pero ahora me aparece que necesito la 2.5.1, no entiendo porque pasa esto.

**Comment by jerosalazar** [comment]
Hola! Corriste docker-compose build? Recuerda que todos los comandos de rails (o bundle o rake) que corras debes anteponerles `docker-compose run web` porque estás trabajando con las dependencias dentro de tu contenedor, no en el computador
