### ISSUE TITLE
[Proyecto] Atributos en Diagrama E/R

### ISSUE THREAD

**Issue by gatochico** [IIC2143-2019-2/proyecto#69]
Hola! Una duda corta: ¿En nuestro diagrama E/R se deben incluir los atributos de cada entidad, o solo estas y las relaciones entre ellas?
Saludos! :cat:

**Comment by jerosalazar** [comment]
Hola! Si es necesario que incluyan los atributos. Depende de sus Product Owners que tan detallado quieren el diagrama, pero la idea es que se pueda entender el funcionamiento de la app. Saludos!
