### ISSUE TITLE
Problema con ejemplo

### ISSUE THREAD

**Issue by cacoos** [IIC2143-2019-2/proyecto#7]
Hola!

Instalé Docker en Windows y al levantar la app me sale esto:

![image](https://user-images.githubusercontent.com/30879716/63969566-1f318e00-ca70-11e9-800d-78d67ddc8b3b.png)

Es problema mío o de la base de datos?

Saludos

**Comment by jerosalazar** [comment]
Revisa en la carpeta tmp/pids si hay un archivo llamado server.pid, si ese archivo tiene un número 3 adentro, borra el archivo en intenta correrlo de nuevo

**Comment by cacoos** [comment]
Tiene un "1" adentro. ¿Qué significa?

**Comment by atbusch** [comment]
Probablemente es porque lo cerraste con ctrl+c. Trata borrando el archivo y corriéndolo de nuevo.

**Comment by cacoos** [comment]
Lo estoy corriendo así ahora y me tira este error

![image](https://user-images.githubusercontent.com/30879716/63978842-637b5900-ca85-11e9-8364-29f51df361f1.png)

**Comment by cacoos** [comment]
De hecho siguiendo los pasos del README, me pasa que al ejecutar el comando
`docker-compose run web rails db:create` resulta en el siguiente error

![image](https://user-images.githubusercontent.com/30879716/63979691-798a1900-ca87-11e9-9a26-9961ece7573a.png)

**Comment by cacoos** [comment]
Ya lo solucioné :)

**Comment by jerosalazar** [comment]
Como lo solucionaste? Quizás le sirve a alguien más

**Comment by cacoos** [comment]
Después de crear la app de rails, en config/database se debe poner 
```
  host: postgres
  username: postgres
  password:
```
dentro de `default:`

mientras que en el docker_compose.yaml debe tener lo siguiente

`version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    env_file:
      - .env
    command: bash -c "(bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/example
    ports:
      - "3000:3000"
    depends_on:
      - postgres`
