### ISSUE TITLE
[Gemas] Simple Form

### ISSUE THREAD

**Issue by ridiazcampos** [IIC2143-2019-2/proyecto#70]
¡Hola! Una duda respecto a las gemas. ¿Es posible utilizar simple_form en el proyecto?

¡Gracias!
Saludos (:

**Comment by isavega** [comment]
[No soy ayudante]: Pero si miras las issues del semestre pasado si estaba permitida

**Comment by vjaguilera** [comment]
Hola! Se me pasó avisar, un grupo había preguntado por interno. SI ESTÁ PERMITIDA!

**Comment by ridiazcampos** [comment]
¡Genial! Muchas gracias c:
