### ISSUE TITLE
docker en virtualbox

### ISSUE THREAD

**Issue by acpopper** [IIC2143-2019-2/proyecto#73]
Hola! perdon y se que es algo tarde, pero he tenido muchos problemas intentando usar docker en virtualbox. Quería saber como resuelvo este problema.
![image](https://user-images.githubusercontent.com/42228405/65572822-9eb35f80-df3f-11e9-8e81-07b649faa812.png)

Ese error aparece tambien cuando intento hacer compose build o con algunos otros comandos. 
Gracias

**Comment by CmPoblete** [comment]
Prueba corriendo lo con sudo.
sudo docker run hello-world

**Comment by CmPoblete** [comment]
Te funcionó?

**Comment by acpopper** [comment]
Hola! 
Si, me cargo la imagen hello-world.
Gracias!
