### ISSUE TITLE
[Gemas] error al correr docker-compose up

### ISSUE THREAD

**Issue by juakoke** [IIC2143-2019-2/proyecto#74]
al hacer el comando me sale el siguiente error:
web_1  | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
web_1  | Bundler::GemNotFound: Could not find bcrypt-3.1.13 in any of the source
trate de solucionarlo haciendo sudo docker-compose gem install bcrypt
tambien añadí a el gemfile la linea " gem 'bcrypt', '~> 3.1.13' " y luego hice sudo docker-compose run web bundle install, pero tampoco funcionó

**Comment by johntrombon** [comment]
Desconozco el origen de tu error pero lo que te puedo decir es que no deberías correr bundle install sino que docker-compose build. Intenta con eso y reporta como te va

**Comment by juakoke** [comment]
copie el archivo de nuevo y con build me funcionó gracias
