### ISSUE TITLE
Asociaciones

### ISSUE THREAD

**Issue by isavega** [IIC2143-2019-2/proyecto#75]
Hola!

En la ayudantia aparece como "error tipico" que no hay que crear una asociacion que haga referencia que a otra que aun no se crea, en el fondo tener cuidado con el orden. Mi pregunta es, si las asociaciones se crean en archivos distintos, por ejemplo: 
app/models/user.rb
app/models/post.rb

Como afecta el orden si son archivos distintos??

Gracias :sweat_smile:

**Comment by CmPoblete** [comment]
Porque la asociacion también se específica en la migracion (eso pasa al hacer references), entonces si creas los posts primero, al correr las migraciones rails va a intentar referenciar la tabla de usuarios en la de los posts, pero como está no ha sido creada va a tirar un error

**Comment by vjaguilera** [comment]
Hola, las asociaciones por lo general siempre se harán hacia entidades que se encuentran en archivos distintos. El problema del orden ocurrirá cuando quieras levantar tu aplicación o si deseas migrar a la base de datos, porque si referencias una entidad que no existe, la máquina no entenderá a quién quieres ligar la entidad que declaraste con una referencia. Espero que eso responda a tu pregunta.

**Comment by isavega** [comment]
Gracias a ambos! Pero mi pregunta es en que archivo especifico debo cuidar el orden, es en migrate/schema.rb?

**Comment by CmPoblete** [comment]
Debes cuidar el orden al crear los modelos
