### ISSUE TITLE
Error al instalar el gem 'devise'

### ISSUE THREAD

**Issue by firulais33** [IIC2143-2019-2/proyecto#76]
Hola,

Agregué el gem **_devise_** al Gemfile y corr'i el comando `docker-compose run web bundle install`, y me dice que no encuentra el gem 'bcrypt'. Lo descargu'e usando `docker-compose run web gem install bcrypt `y no funcion'o. Tambi'en lo hice agregandolo desde el Gemfile, pero aun as'i no lo encuentra al tratar de instalar _**devise**_

**Comment by ridiazcampos** [comment]
¡Hola! Puede que sirva el comando `sudo docker-compose build` (el mismo del tutorial :D). Al parecer, dentro de tooodas las cosas que hace, ejecuta `bundle install` (creo que es porque está en el Dockerfile), y ve el tema de las gemas. No estoy seguro si sea la solución correcta jaja, pero parece funcionar!

¡Saludos! (:

**Comment by vjaguilera** [comment]
Hola, como dice @ridiaz2 intenta hacer bundle install para incluir todas las gemas en el ambiente de trabajo. Trata de instalar todas las gemas directamente en el Gemfile y correr bundle install.
