### ISSUE TITLE
Tengo un error al crear un index controller

### ISSUE THREAD

**Issue by isavega** [IIC2143-2019-2/proyecto#77]
Hola,

Creamos los CRUDS y funcionan pero nos faltaba un index, por lo que por mi parte cree un controlador con:
sudo docker-compose run web rails g controller Welcome index

Modifique las views y las rutas pero al momento de probar si funcionaba me tira este error:

![image](https://user-images.githubusercontent.com/42187168/65719807-f60b1a00-e07c-11e9-9832-70698856c9e4.png)

![image](https://user-images.githubusercontent.com/42187168/65719826-04593600-e07d-11e9-80cf-9273138cdb2a.png)

Muchas gracias!!

**Comment by jerosalazar** [comment]
Hola! prueba con la solución a la que llegó otro compañero en #72. Las causas son distintas, pero el error que sale es el mismo, quizás te lo pueda solucionar. En todo caso vamos a revisar que puede ser y te respondemos. Saludos!

**Comment by isavega** [comment]
Por una extraña razón, al otro dia se arregló solo. No hice nada 🤕  Pero muchas gracias jajajaj
