### ISSUE TITLE
Casilla formato datetime CRUD comentarios

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2143-2019-2/proyecto#78]
Hola, tengo una duda sobre como hacer que aparezca en la pagina del formato, fecha y hora al escribir un nuevo comentario, segun la documentacion debería ser de esta forma:

![Captura de pantalla de 2019-09-26 22-49-52](https://user-images.githubusercontent.com/47841749/65736030-04265e00-e0b0-11e9-9031-3c0fc06c0c0c.png)

Pero me aparece asi:

![Captura de pantalla de 2019-09-26 22-50-45](https://user-images.githubusercontent.com/47841749/65736057-199b8800-e0b0-11e9-8223-ae445ef864ee.png)

Es decir como formato de texto, por lo que sería difícil para un usuario ingresar el dato correctamente, lo que me gustaria es que aparezca de esta forma:

![Captura de pantalla de 2019-09-26 22-52-04](https://user-images.githubusercontent.com/47841749/65736096-46e83600-e0b0-11e9-89ba-465caadaae1b.png)

O algo por el estilo, pero incluyendo la fecha, no se si tienen alguna idea de cual es el problema?

Saludos

**Comment by jerosalazar** [comment]
Hola!

Busca en internet los `form tags` que posee rails. Ahí te pueden salir otros _field types_ que puedes ocupar en tu formulario, como algun selector de datetime, o fields distintos para la fecha y la hora, como más te acomode
