### ISSUE TITLE
Gemas permitidas/No permitidas para el proyecto semestral

### ISSUE THREAD

**Issue by jerosalazar** [IIC2143-2019-2/proyecto#79]
Hola a todos! 

En esta issue se va a llevar un listado con las gemas permitidas y no permitidas para ocupar en el proyecto. Es importante que siempre **pregunten** antes de comenzar a implementar una gema, para que no tengan problemas a futuro.

Para consultar sobre una gema o servicio deberán comentar este issue con una pregunta de la siguiente forma:

> ¿Puedo utilizar la gema "nombre_librería" para hacer “explicación-de-lo-que-quiero-hacer”?

# Gemas Permitidas
* ```simple-form```
* ```cancan```
* ```active admin```
* ```gmaps4rails```
* ```jquery-rails```
* ```bootstrap```
* ```popperjs```
* ```omniauth-facebook```

# Gemas No Permitidas

**Comment by cristianoberpaur** [comment]
¿Puedo utilizar la gema "cancan" para hacer “el manejo de los distintos tipos de usuarios”?

**Comment by jerosalazar** [comment]
@cristianoberpaur si se puede 👌

**Comment by aortiz2407** [comment]
¿Puedo utilizar la gema "active admin" para hacer “obtener vistas de administración"?

**Comment by aortiz2407** [comment]
¿Puedo utilizar la gema "cancancan" para hacer “manejo de permisos"?

**Comment by atbusch** [comment]
Hola @aortiz2407 se pueden usar las dos gemas

**Comment by kylevon** [comment]
¿Puedo utilizar la gema "active storage" para manejo de imágenes?

**Comment by mjretamales** [comment]
Hola ¿Se puede utilizar la gema activemerchant para crear un carro de compras?

**Comment by ariela1** [comment]
¿Puedo utilizar la gema "Gmaps4rails" para poner mapas en la aplicación?

**Comment by johntrombon** [comment]
@kylevon Si se puede! ojo que la versión de rails de tu aplicación debe ser >= 5.2. Si tienen una versión de rails más antigua pueden usar Carrierwave como alternativa

**Comment by vcoello** [comment]
¿Puedo usar las gemas "jquery-rails", "bootstrap" y "popperjs" para generar vistas con modals?

**Comment by jerosalazar** [comment]
@vcoello Si, puedes ocupar todas

**Comment by ariela1** [comment]
¿Puedo utilizar la gema "omniauth" y "omniauth-facebook" para poner agregar inicio de sesión con facebook en la aplicación?

**Comment by ariela1** [comment]
¿Puedo utilizar la gema "omniauth-facebook" para iniciar sesion con facebook en la aplicación?

**Comment by jerosalazar** [comment]
@ariela1 si, se puede ocupar
