### ISSUE TITLE
[Docker] Problema instalación en Windows 10

### ISSUE THREAD

**Issue by jmsilvas** [IIC2143-2019-2/proyecto#8]
Hola, al tratar de instalar Docker Desktop me sale el siguiente error:
![image](https://user-images.githubusercontent.com/42247208/64033879-6f195f00-cb1b-11e9-91e3-78aefecfdd43.png)
Por lo que al parecer no es compatible con mi Windows 10 (Home), es suficiente descargar Docker Toolbox en este caso? O existe alguna forma de tener la versión Desktop?

**Comment by jerosalazar** [comment]
Hola! Intenta ver si te funciona con toolbox, si no puedes revisar otras opciones, como crear una maquina virtual
