### ISSUE TITLE
Conflicto de user

### ISSUE THREAD

**Issue by maogaz** [IIC2143-2019-2/proyecto#80]
Hola, 
si creamos un usuario con Scaffold con nombre "user" y al hacer el tutorial para usar Devise creamos otro "user", tendrá conflicto?

**Comment by dagalloso** [comment]
Hola! Devise hace todo lo necesario para el manejo de sesiones, entre eso crear el modelo correspondiente. Si crean un modelo de Devise con un nombre distinto a "user" no debería generarles ningún problema. No puedo asegurar nada en el otro caso, pero no lo recomendaría tampoco.
