### ISSUE TITLE
Error base de datos 

### ISSUE THREAD

**Issue by dacampos1** [IIC2143-2019-2/proyecto#81]
Hola!, he estado teniendo problemas con  la base de datos, el localhost me arroja el siguiente error y cuando uso el comando que dice también tengo error
![Captura de Pantalla 2019-09-28 a la(s) 14 19 01](https://user-images.githubusercontent.com/42916420/65820081-460feb00-e1fb-11e9-813d-b9c76f2041bf.png)
![Captura de Pantalla 2019-09-28 a la(s) 14 19 44](https://user-images.githubusercontent.com/42916420/65820083-49a37200-e1fb-11e9-9c14-bf0bc9a5b960.png)

**Comment by CmPoblete** [comment]
Hola, debes migrar la base de datos usando docker. El comando es docker-compose run web rails db:create

**Comment by fediaz3** [comment]
Hola, estoy en el mismo problema, no he podido encontrar la solución y no me sirven las opciones de arriba :/
