### ISSUE TITLE
[Proyecto][Heroku]

### ISSUE THREAD

**Issue by Tsoublette** [IIC2143-2019-2/proyecto#82]
La app corre perfecto en docker, pero al subirla a heroku me pidió hacer un archivo heroku.yml o usar el comando "heroku stack:set heroku-18". Usé la segunda opción, y al hecer push en heroku, se cae la app y me pide que revise mis logs, recomendando el comando "heroku logs --tail".

**Comment by baaldana** [comment]
Hola, a nosotros nos está pasando lo mismo.
![imagen](https://user-images.githubusercontent.com/42224818/65839160-3965c280-e2e1-11e9-8447-7935000a49cd.png)

**Comment by Tsoublette** [comment]
No era necesario hacer el archivo .yml, usamos "docker-compose heroku run rake db:migrate", y ahi se migró la base de datos

**Comment by juakoke** [comment]
intente con el "docker-compose heroku run rake db:migrate" pero aparece que heroku no es una accion de docker-compose

**Comment by Tsoublette** [comment]
quizás prueba sin el docker-compose
