### ISSUE TITLE
Error haciendo scaffold

### ISSUE THREAD

**Issue by acpopper** [IIC2143-2019-2/proyecto#83]
Hola! Cuando intento hacer un scaffold con este comando (maquina virtual ubuntu):
rails generate scaffold comentario id_comentario:integer fecha:date texto:text
me aparece esto:
![recorte 1](https://user-images.githubusercontent.com/42228405/65827625-848fbf00-e268-11e9-88d4-477e1e9b37fd.JPG)

Cual podría ser el problema?

**Comment by vtespinosa** [comment]
Hola, recuerda que como la app está creada con docker debes poner: docker-compose run web antes de los comandos de rails. En este caso el comando quedaría asi:
docker-compose run web rails generate scaffold .....

**Comment by vjaguilera** [comment]
Hola! Podrías mandar una foto de tu Gemfile y tu Gemfile.lock?

**Comment by acpopper** [comment]
Ahí si resultó, gracias!
