### ISSUE TITLE
[Heroku] Problema al hacer push.

### ISSUE THREAD

**Issue by nep0s** [IIC2143-2019-2/proyecto#84]
Hola! Cuando trato de subir la aplicación al servidor me salta un error por no poder instalar algunas gemas.
![Screenshot from 2019-09-29 21-37-53](https://user-images.githubusercontent.com/48266811/65842404-a7ba7d00-e301-11e9-98e1-1267cfb6d678.png)
¿Hay alguna forma de solucionarlo?
Gracias!

**Comment by camichavez** [comment]
hola! pudiste arreglarlo?

**Comment by nep0s** [comment]
No todavía.

**Comment by camichavez** [comment]
Si lo llegas a arreglar me comentas por favor!

**Comment by nep0s** [comment]
Lo probé de nuevo en otra aplicación de heroku y me funcionó.
