### ISSUE TITLE
docker-compose permiso denengado

### ISSUE THREAD

**Issue by martucoss** [IIC2143-2019-2/proyecto#85]
Al ocupar máquina virtual de ubuntu, puedo instalar docker-compose, pero no puedo ocupar el comando docker-compose, porque me dice que está denegado el permiso. Alguien sabe alguna solución?

**Comment by CmPoblete** [comment]
Hola, debes anteponer sudo para que funcione (sudo docker-compose).

**Comment by johntrombon** [comment]
Si puedes adjuntar un pantallazo del error ideal! (tengo entendido que te falla aunque antepongas sudo)

**Comment by martucoss** [comment]
Lo logré solucionar, gracias.
