### ISSUE TITLE
[Proyecto] Diseño

### ISSUE THREAD

**Issue by conikuschel** [IIC2143-2019-2/proyecto#86]
Para el diseño de la pagina web se pueden usar plantillas que tengan el código HTML, archivos CSS y usen bootstrap o la idea es partir el diseño desde 0?

**Comment by jerosalazar** [comment]
Hola! Pueden usar plantillas o librerias que los ayuden con el estilo de su aplicación. La ayudantía de mañana hablará un poco sobre esto mismo 😊
