### ISSUE TITLE
[Proyecto] [devise]

### ISSUE THREAD

**Issue by Tsoublette** [IIC2143-2019-2/proyecto#87]
Luego de instalar las gemas con bundle install, al intentar instalar devise nos aparece que falta la gema bcrypt (a pesar de que al correr bundle aparece específicamente que esta gema se instala). Hemos tratado de instalar bcrypt de muchas formas distintas, pero igual no funciona.
Además, después de fallar la instalación de devise, la app se cae y deja de funcionar (hemos tenido que crear varias apps nuevas)

**Comment by jerosalazar** [comment]
Hola, estas instalando las gemas con ```bundle install``` o con ```docker-compose build```? recuerda que todas las gemas debes instalarlas a traves de docker
