### ISSUE TITLE
Bootstrap-sass 

### ISSUE THREAD

**Issue by isavega** [IIC2143-2019-2/proyecto#88]
Hola,

Instale la gema Bootstrap-sass siguiendo su documentación y al parecer, esta gema tiene entre sus dependencias autoprefixer. Por lo que que al correr el servidor, me decia que me faltaba esta gema. 

La instale en mi Gemfile, corrí bundle install y nada... En internet hay varios comentarios que apuntan a borrar el cache con rake tmp:clear pero me tira el mismo problema. No tengo la gema autoprefixer a pesar de instalarla (me tira que se instaló exitosamente). También probé con bundle install --path vendor/cache y nada. 

Que puede ser? Llevo horas pegada jajajaj Muchas gracias!

![image](https://user-images.githubusercontent.com/42187168/66785274-24795980-eeb3-11e9-801d-e19d956a324b.png)

![image](https://user-images.githubusercontent.com/42187168/66785305-3fe46480-eeb3-11e9-9c6a-2e20880180e3.png)

**Comment by mvgil** [comment]
Hola! instala la gema con el comando docker-compose build, con ese comando se ejecuta también bundle install.

**Comment by isavega** [comment]
Funcionó, no puedo creer que era tan simple. Solo por saber, por que mis comandos no funcionaban?

**Comment by mvgil** [comment]
Al hacer docker-compose build se reconstruye la imagen con las nuevas actualizaciones de tu gemfile. Así, la nueva imagen construida tiene instaladas las nuevas gemas. (que se instalan porque al correr docker-compose build, se ejecuta bundle install).

**Comment by isavega** [comment]
Muchas gracias 😄
