### ISSUE TITLE
Error al migrar bd. "uninitialized constant RolifyCreateRoles"

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2143-2019-2/proyecto#89]
Hola, al momento de migrar la base de datos, me aparece el siguiente error: "uninitialized constant RolifyCreateRoles". Creo que tiene que ver con la gema rolify, seguí todos los pasos para instalarla y tambien generé el archivo role.rb.

**Comment by daleal** [comment]
Hola! Luego de agregar la gema a tu `Gemfile`, ejecutaste `docker-compose build`?
