### ISSUE TITLE
[Tarea] - Duda formato método "cantidad_de_alumnos sin_reprobar_ramos()"

### ISSUE THREAD

**Issue by jpgonzalez4** [IIC2143-2019-2/proyecto#9]
Hola.
Para el output del método cantidad_de_alumnos sin_reprobar_ramos() no queda específicado el formato que debe tener la lista de alumnos que viene luego de la cantidad. ¿Debo poner los nombres de los alumnos, sus IDs o las instancias completas creadas de clase Alumno?
Gracias

**Comment by vjaguilera** [comment]
Hola!
El formato debe ser análogo a **alumnos_aprobados()**. La idea es que la lista tenga los nombres de los alumnos de la forma: [alumno_1, alumno_2, ... , alumno_n].
Perdón de antemano, se nos pasó esa especificación!

Saludos.

**Comment by alexaptib** [comment]
@vjaguilera Acabo de revisar el enunciado y para alumnos_aprobados indica que el formato es alumno_1, alumno_2, ... , alumno_n, no [alumno_1, alumno_2, ... , alumno_n]. Da lo mismo? Como se debe colocar?

**Comment by vjaguilera** [comment]
@alexaptib Para ambos métodos (**alumnos_aprobados()** y **cantidad_de_alumnos_sin_reprobar_ramos()**) se debe retornar **los nombres**, pero el formato es distintos en ambos:
- **alumnos_aprobados()** retorna los nombres **sin corchetes**
- **cantidad_de_alumnos_sin_reprobar_ramos()** retorna los nombres **dentro de corchetes**.

**Comment by jpgonzalez4** [comment]
Pensé que los corchetes no se escribían, porque representan un valor dentro de un string, como en el caso de 
Promedio del curso {sigla del curso}: {promedio calculado}.
Debería ser:
Promedio del curso ABC1234: 6.7
o
Promedio del curso {ABC123}: {6.7}
??

**Comment by vjaguilera** [comment]
El primer caso que pusiste

**Comment by jpgonzalez4** [comment]
entonces los nombres de *cantidad_de_alumnos_sin_reprobar_ramos()* no van dentro de corchetes, sino que uno despues de otro, separados por comas

**Comment by vjaguilera** [comment]
@jpgonzalez4 quizás con este ejemplo te quede más claro:
- **alumnos_aprobados()**: 
_Alumnos aprobados del curso IIC2513: 30, Jerónimo Salazar, Victoria Gil, ..._
- **cantidad_de_alumnos_sin_reprobar_ramos()**:
_Alumnos sin reprobar: 20, [Cristobal Poblete,  Vicente Aguilera, .... ,]_

**Comment by gatochico** [comment]
Hola @vjaguilera ! Leyendo tu última respuesta veo que pusiste en el output de **alumnos_aprobados()** un número (30) que asumo es la cantidad de alumnos aprobados. Sin embargo, en el enunciado no se pide la cantidad de alumnos aprobados sino solo enumerarlos. ¿Cuál de los dos formatos sigo?
Gracias de antemano!

**Comment by vjaguilera** [comment]
Toda la razón @gatochico, solo es enumeración, omite el 30. Perdón, mala mía.
