### ISSUE TITLE
[Entrega Proyecto]

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2143-2019-2/proyecto#90]
Hola!
Hablando con algunos compañeros, varios tenemos varias entregas acumuladas para la fecha del viernes, y nos preguntabamos si podrían correr la fecha de la entrega.
Desde ya gracias!

**Comment by jerosalazar** [comment]
Hola, lamentablemente no se puede postponer la fecha de la entrega. El calendario del proyecto se publicó a principio de semestre para que puedan organizarse y, exceptuando casos especiales como el pasado paro, este no será modificado.

Ánimo con la entrega, saludos!
