### ISSUE TITLE
[active admin]

### ISSUE THREAD

**Issue by mjretamales** [IIC2143-2019-2/proyecto#91]
Hola!
Me sale este error cuando agrego la gema activeadmin al Gemfile y corro docker-compose build (o cualquier otro comando). Intente con distintas versiones de la gema y siempre sale el mismo error. 

ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 6

![Captura de pantalla 2019-10-15 a la(s) 9 55 54 p  m](https://user-images.githubusercontent.com/42184158/66879865-a0000700-ef96-11e9-8dd3-a57140a306c7.png)

**Comment by daleal** [comment]
Hola! Intenta vaciar el contenido de tu `Gemfile.lock` y volver a correr el comando, dejando un `Gemfile.lock` totalmente vacío antes de ejecutarlo.
