### ISSUE TITLE
Error db:create

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2143-2019-2/proyecto#92]
Hola, me empezó a arrojar el siguiente error al tratar de crear la base de datos, alguna idea de por qué?

![image](https://user-images.githubusercontent.com/47841749/66881643-e60c9900-ef9d-11e9-8af3-708093d45a02.png)

**Comment by daleal** [comment]
Hola! Si antes podías crear la base de datos y ahora no, mi apuesta es que cambiaron el `docker-compose.yml`, específicamente la línea que dice `volume:` y ahora tu sistema operativo no encuentra la dirección especificada debido a que no la encuentra. Ve en tu historial de GitHub y trata de encontrar si cambiaron el archivo o no.
