### ISSUE TITLE
Problema de almacenamiento VirtualBox

### ISSUE THREAD

**Issue by acpopper** [IIC2143-2019-2/proyecto#93]
Hola, ayer podía abrir la aplicación sin problemas en la máquina virtual, y cada vez que usaba la máquina me salía que quedaba menos memoria. Ahora me salen 0 bytes disponibles y no me deja correr la aplicación. Cómo puedo solucionar esto?
![low memory virtual box](https://user-images.githubusercontent.com/42228405/66939776-172aaf00-f01a-11e9-95fc-a90d29034e58.JPG)

**Comment by acpopper** [comment]
Vi en una página que estos comandos podían entregar información útil respecto al problema:
![dh -h](https://user-images.githubusercontent.com/42228405/66940918-39bdc780-f01c-11e9-97d8-3af5d1803ad4.JPG)
![sudo parted -l](https://user-images.githubusercontent.com/42228405/66940941-493d1080-f01c-11e9-8ada-a2a5a8830aa5.JPG)

**Comment by daleal** [comment]
Hola! Probablemente tienes varias imágenes instaladas en tu computador. Lo que te recomiendo es hacer `docker system prune -a`, lo que elimina todos los contenedores y todas las imágenes del sistema. Luego de esto, tendrías que vovler a hacerle build a tu Dockerfile para generar una imágen nueva. Ojalá que te sirva! (Igual, tomando en cuenta lo pequeña que es tu partición, lo veo muy probable que en un futuro no tan lejano tengas que volver a hacer eso, y quizás ni siquiera eso sea suficiente. Como solución a más largo plazo, trata de agrandar el tamaño de tu máquina virtual)

**Comment by acpopper** [comment]
Gracias! Eso ayudó
