### ISSUE TITLE
Cambiar atributos al clickear un link

### ISSUE THREAD

**Issue by elisafdz** [IIC2143-2019-2/proyecto#95]
Hola!
Estoy tratando de hacer que cuando se hace click en el link aceptar solicitud, el atributo aceptado del restaurant se vuelva true. Para esto estoy haciendo lo siguiente pero el atributo no se cambia. He probado varias otra formas que me aparecieron en internet pero ninguna me funciona. Agradecería muchísimo si me pudieran ayudar.
este es el link
 <td><%= link_to 'aceptar solicitud', restaurants_path, {:controller => "restaurants", :action => "aceptar", :nombre => restaurant.nombre}%>

y este el método en el controller de restaurantes
def aceptar
    restaurant = Restaurant.find(params[:nombre])
    restaurant.aceptado = True
    restaurant.save()
  end 

Gracias

**Comment by daleal** [comment]
Hola! Te sale algún tipo de error cuando haces click en el link? Si es así, podrías mostrarlo por acá para ver exactamente qué está pasando?

**Comment by daleal** [comment]
Después de pensar un rato, `CREO` que no funciona tu código porque ese link no te está redirigiendo correctamente a la acción del controlador a la que quieres dirigirte **O** porque la forma en que estás adquiriendo el restaurant en el controlador es errónea (no estoy seguro la verdad porque tendría que ver el output), pero creo que quizás esto te sirva (asumo que en tu `config/routes.rb` tienes una línea algo como `get 'restaurants/aceptar', to: 'restaurants#aceptar'`):

En la acción del controlador en que se quiere aceptar la solicitud (digamos que es el controlador de `Admin` en la acción `accept_restaurant`) cargas el restaurant como una variable (algo como `@restaurant = Restaurant.find(params[:restaurant_id])`). Luego, en la vista puedes acceder a `@restaurant` y usar eso para redirigirte a la acción del restaurant en específico que quieres editar, con un link tipo `link_to "Accept", restaurants_aceptar(@restaurant)`. Eso te llevaría a la acción `aceptar` del controlador `Restaurants`. De ahí deberías poder editar los atributos que necesites, encontrando el restaurant en específico como `@restaurant = Restaurant.find(params[:id])`. Esto funciona porque lo que hace la línea `link_to "Accept", restaurants_aceptar(@restaurant)` es llamar a la acción `aceptar` del controlador `Restaurants` con los atributos de `@restaurant` como parámetros de la request `GET`, por lo que dentro del controlador, `:id` es el `id` de `@restaurant` (probablemente no debería ser un `GET` en todo caso).

Solo para ser un poco más amplio en la respuesta, si en tu controlador `Admin` quieres cargar **todos** los restaurants, o al menos varios, con una línea tipo `@restaurants = Restaurant.all` y luego en tu vista quieres ponerle un botón a cada restaurant, también es válido tener algo como lo siguiente:

```ruby
@restaurants.each do |restaurant|
    link_to "Accept", restaurants_aceptar(restaurant)
end
```

Espero haber respondido la duda!

**Comment by elisafdz** [comment]
Hola! muchas gracias por la respuesta. El problema es que no hay un
controlador admin, esto es solamente un bool que determina que usuario es
administrador o no. cree una nueva ruta a la que se accede al clickear
solicitudes pendientes esta se ve como la foto que adjunto a continuación,
desde el view correspondiente a ese path muestro los restaurantes que no
han sido aceptados junto con el link que debiese hacer que se ejecute la
función aceptar del controller restaurantes. Quizás no entendí de manera
correcta lo que me propusiste que hiciera pero creo que no es aplicable
para mi caso. Adjunto fotos de routes, controller de restaurante y
about(view donde estan las solicitudes pendientes).
Muchas gracias nuevamente

**Comment by daleal** [comment]
Hola! La foto no se subió :( pero si te entiendo bien, entonces igual deberías poder aplicarlo. Lo que me estás diciendo es que en realidad el controlador `Admin` no existe y que tienes una vista donde muestras todos los restaurants aún pendientes por aceptar junto con un link. Ese link debería ser de la forma `link_to "Accept", restaurants_aceptar(restaurant)` y eso te debería llevar al controlador y acción deseada, donde puedes buscar el restaurant usando su `:id`

**Comment by elisafdz** [comment]
Perdón, se que sería vas fácil darse cuenta del problema con fotos pero no se por que no puedo mandarlas, he tratado varias veces y no las sube.  Al hacer lo que me dices (link_to 'Accept', restaurants_aceptar(restaurant)  me aparece el error: 
undefined method `restaurants_aceptar' for #<#<Class:0x00007ff0f401f918>:0x00007ff0edab5f00>
y si cambio restaurants_aceptar por restaurants_aceptar_path aparece el error:
Couldn't find Restaurant without an ID
y subraya la linea dentro de aceptar en el controller restaurant: restaurant = Restaurant.find(params[:id])
Perdón por la cantidad de preguntas pero llevo todo el día tratando que funcione y no logro arreglarlo.

**Comment by daleal** [comment]
Uuuh mala mía, olvidé agregarle `_path` a todas las cosas. Lo que yo haría en ese caso sería tratar de debuguear viendo qué parámetros se envían para cada acción. Para hacer eso, puedes editar el archivo `app/views/layouts/application.html.erb` y pegar la siguiente línea de código: `<%= debug(params) if Rails.env.development? %>` justo antes de la línea que dice `</body>`, de manera que te quede algo como esto:

```html+erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>
```

Lo que hace esa línea es que, si la app está corriendo en development, muestra al final de la vista todos los argumentos con los que se cargó el controlador. Con eso, puedes hacer que tu controlador `Restaurants`, cuando llames a la acción `aceptar`, no haga nada dentro del controlador y solo cargue una vista vacía. Así puedes ver exactamente qué variables está recibiendo el controlador y qué variables no.
