### ISSUE TITLE
Error devise

### ISSUE THREAD

**Issue by jjverschueren** [IIC2143-2019-2/proyecto#96]
![Screenshot_2019-10-17_20-45-58](https://user-images.githubusercontent.com/37182471/67055842-04020700-f120-11e9-9794-d1833c417162.png)

Cuando agrego la gema devise al Gemfile, me tira este error cuando hago docker-compose build, no entiendo que podria ser

**Comment by daleal** [comment]
Hola! Pueden haber 2 problemas que causan eso. Uno es que tu conexión a internet sea inestable o inexistente. En ese caso, deberías ir a algún lugar con conexión más estable. La otra razón por la que podría ocurrir eso es que sea una incompatibilidad del daemon de docker con y el kernel de linux (si esto ocurrió, probablemente actualizaste docker/tu kernel hace poco). En ese caso, te recomiendo hacer un downgrade a la versión anterior de lo que sea que actualizaste hace poco hasta que se estabilice y luego volver a hacer el upgrade.

**Comment by jjverschueren** [comment]
Era el internet, Gracias!
Igual raro porque estaba usando el internet de la u y mi compañero al lado tambien lo estaba usando y si le funcionaba. Pero se arreglo cuando llegue a mi casa asi que todo bien

**Comment by daleal** [comment]
Me pasó también por un tiempo. Al final lo que hice fue reinstalar Docker y se arregló :laughing:
