### ISSUE TITLE
2 versiones de postgresql distintas

### ISSUE THREAD

**Issue by Cadagan** [IIC2143-2019-2/proyecto#98]
Esperando que esten bien, mi problema es que al correr el `sudo docker-compose up` me arroja el siguiente resultado

> db_1   | 2019-10-18 14:18:21.518 UTC [1] FATAL:  database files are incompatible with server
db_1   | 2019-10-18 14:18:21.518 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.0 (Debian 12.0-2.pgdg100+1).
blog_db_1 exited with code 1

Alguna idea de que podria ser? en stackoverflow lo unico que encontre fue [este link de volver a un contenedor previo](https://stackoverflow.com/questions/44221938/postgres-container-crashes-with-database-files-are-incompatible-with-server-af) o algo asi (a mi no me sirvio pero tal vez a alguien mas le sirva 🤷‍♂️)

Extra: en mi pc tengo postgresql 10, asi que no logro entender el problema :(

**Comment by daleal** [comment]
Hola! Esto ocurre cuando inicializas el volumen para la base de datos con una versión de postgres y luego tratas de usarla con otra versión de postgres. Lo más probable es que hayas inicializado el volumen con una imágen de posgresql y que luego se haya actualizado (hace poco salió la versión estable de la imágen de postgres 12), por lo que ahora no puedes acceder a ese volumen. Mi recomendación es que corras `docker volume ls` para ver qué volúmenes tienes en tu computador y que luego selecciones el volumen que contiene los datos de tu app y corras `docker volume rm {volume_id}` (en caso de que no te importe ningún otro volumen, puedes simplemente correr `docker volume prune`).

**Comment by miguelramirezv** [comment]
Hola! A mi me pasó lo mismo cuando actualicé a la última versión de Docker hace 4 días y sigo con el mismo problema aunque reinstalé Docker y Postgresql. 

Hablando de la solución propuesta, viendo docker volume ls no tengo ningún volumen por lo que el problema no creo que está ahí.

Parece que el problema es ese de dos versiones o instancias de postgresql, pero no he logrado encontrar la solución! Por si me pudieran ayudar. Muchas gracias!!

**Comment by daleal** [comment]
Por favor muestrame el contenido de tu `docker-compose.yml`

**Comment by miguelramirezv** [comment]
Es este:

version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ticket-app
    ports:
      - "3000:3000"
    depends_on:
      - db

**Comment by daleal** [comment]
Anda a la carpeta en que tienes tu `docker-compose.yml` y borra la carpeta `tmp`. Luego, vuelve a levantar el servidor (el problema era el que dije antes, solo que la información del volumen se guarda en la carpeta `tmp` pero no encontrabas ningún volúmen con `docker volume ls` porque tus volumenes estaban detenidos). Lo que va a hacer esto es forzar al contenedor de `postgres` a recrear la carpeta en que guarda la información de su volumen y así se va a inicializar con postgres 12 y no postgres 11. Dime si te funciona!

**Comment by miguelramirezv** [comment]
Me funcionó! Se solucionó ese problema pero ahora se me apareció otro problema. Al hacer docker-compose up me aparece:

db_1   | 2019-10-23 00:39:19.961 UTC [1] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2019-10-23 00:39:19.961 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-10-23 00:39:19.962 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-10-23 00:39:19.969 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-10-23 00:39:20.083 UTC [22] LOG:  database system was shut down at 2019-10-23 00:39:08 UTC
db_1   | 2019-10-23 00:39:20.118 UTC [1] LOG:  database system is ready to accept connections


En todo caso yo estoy usando Postgresql 11, debería actualizarlo al 12?

**Comment by daleal** [comment]
Que bueno que se solucionó! Eso que sale ahí no es un error, es lo que siempre sale cuando inicias el contenedor de postgres. En realidad estás usando postgres 12, ya que esa es la versión de postgres que hay en la imagen `postgres` que pulleas en tu `docker-compose.yml`. Como el problema se solucionó, cierro la issue.

**Comment by miguelramirezv** [comment]
Muchas gracias!

Sin embargo, sigo con el problema de que la página no se carga. Es decir, no se puede ver la página subida pero mis compañeros sí, dónde podría estar el problema aquí?
