### ISSUE TITLE
Heroku Error "Precompiling assets failed"

### ISSUE THREAD

**Issue by csolguin** [IIC2143-2019-2/proyecto#99]
Estimados,
Me ocurre el siguiente error al hacer deploy en Heroku,

![Screenshot from 2019-10-18 12-02-55](https://user-images.githubusercontent.com/33853290/67128176-47687e00-f1d1-11e9-8f77-e78a76b834ec.png)
![Screenshot from 2019-10-18 12-04-04](https://user-images.githubusercontent.com/33853290/67128180-4b949b80-f1d1-11e9-8398-3a84a578eff2.png)

Ya he buscado en google, pero ninguna solucion me ha funcionado,Hay alguna forma de solucionarlo?

**Comment by daleal** [comment]
Hola! El error en la precompilación de los assets puede ser por muchas razones. Recomiendo correr el comando `docker-compose run web rails assets:precompile` antes de deployear a heroku para que los assets no los tenga que deployear heroku y así, si falla, puedas ver qué error hay
